appsignal/appsignal-elixir

GettingStarted.md
Very small typo in the GettingStarted guide but it seems, from [config.exs](https://github.com/appsignal/appsignal-elixir/blob/master/lib/appsignal/config.ex), that the key is `enable_host_metrics` and not `enable_host_metric`
=> Fix host metrics config key in GettingStarted

lib/appsignal/phoenix.ex
before, if an exception was raised during processing the transaction, the stacktrace for that exception was sent.
=> remember original stacktrace in phoenix endpoint

lib/appsignal/config.ex, test/config/appsignal_config_test.exs
Ignored errors will be implemented in the agent, this patch sets the configuration option in the system ENV.
=> Set APPSIGNAL_IGNORE_ACTIONS from config

GettingStarted.md
When running the tests it's probably undesirable to be sending events to
AppSignal. There can be *a lot* of them. Add a suggestion to show how to
disable them.
=> Add a section suggesting active: false in test env

.travis.yml
Only build master and develop branches when pushed. When a PR is made on GitHub travis will start a build as well.
This change  prevents two builds being started for one change, like you can see in PR #61 under "All checks have passed - 2 successful checks".
This PR only triggers one build as you can see below.
- I push a branch to make a PR (a build is triggered on TravisCI)
- I make a PR on the repo (a build is triggered on TravisCI)
- one build triggered
- two builds triggered
- build branches "master" and "develop" on push
- build PRs when created.
- other branches are ignored on push
This is the same behavior we have on the Ruby gem repo: https://github.com/appsignal/appsignal-ruby/pull/131
=> Configure Travis builds for branches and PRs

lib/appsignal/phoenix.ex, lib/appsignal/transaction.ex, test/transaction/transaction_test.exs
We assume that a list with a tuple as its first element is an unformatted stack trace. In that case we'll call `Appsignal.ErrorHandler.format_stack/1` on it in `Appsignal.Transaction.set_error/4`, so modules that call it don't need coupling with `Appsignal.ErrorHandler`.
=> Appsignal.Transaction.set_error/4 handles unformatted stacktraces

lib/appsignal/utils/params_filter.ex, test/transaction/filter_test.exs
Enjoying AppSignal with Elixir so far, but I noticed an issue where our users' passwords are showing up in the parameters section on the website, which is no bueno. It looks like this is due to how the filter parameters are being grabbed from Phoenix. The [default parameters for Phoenix](https://github.com/phoenixframework/phoenix/blob/d88a34ec5d316d6f9379f63d41d149df259c9813/mix.exs#L42) live in `Application.get_env(:phoenix, :filter_parameters)` instead of `:config`, so this isn't properly grabbing the defaults and secrets are being sent.
Also, I'll submit a PR for a fix with the docs. For setting it with AppSignal's filtering, it *does* check `:config`, but the docs don't mention that.
=> Add fix for grabbing filter_parameters from Phoenix

mix_helpers.exs
`Mix.Appsignal.map_arch/1` was missing for Alpine, this should add it.
=> Add Alpine linux

lib/appsignal/demo.ex, lib/appsignal/instrumentation/helpers.ex, lib/mix/tasks/appsignal.demo.ex, mix.exs, mix.lock, test/demo_test.exs
As currently present in our Ruby gem as well:
appsignal/appsignal-ruby#199
The "appsignal.demo" command is useful for debugging AppSignal and
testing AppSignal. It's also being used for the Ruby gem installer at and installation UI on AppSignal.com the moment.
It sends a demonstration sample for an error and a performance issue.
They will show up on AppSignal.com as demonstration samples with a small
special UI attached to them describing their purpose.
Debugging manual referencing the "demo" command:
http://docs.appsignal.com/support/debugging.html
Based on #68 
Closes #46
=> Add appsignal.demo mix task

lib/appsignal/error_handler.ex, lib/appsignal/transaction.ex, test/appsignal/error_handler/error_matcher_test.exs, test/appsignal/error_handler/normalize_reason_test.exs
Fix for #76
Note that backend strips all non-alphanumeric characters from the error reason string anyway.
Before and after:
=> Normalize reason string

lib/appsignal/instrumentation/decorators.ex, test/appsignal/instrumentation/decorator_test.exs
Sometimes, specially using background jobs libraries, the function names are always the same (like `perform`), while the module name differentiate the actions (`EmailDeliverWorker`, `CacheUpdateWorker`, ...).
This fix adds the module name to the action name, so it resembles more the action names of controllers.
=> Add the module name to the transaction action while using decorators

lib/appsignal/utils/data_encoder.ex
This support used to exist, but was dropped when `ParamsEncoder` was replaced by `DataEncoder`.
I added a clause to specifically handle atoms (to maintain the `:data` -> `"data"` behavior), and switched the `to_string` to a `inspect` call in the catch-all clause.
=> Readded support for pids and refs inside payloads

lib/appsignal/nif.ex, mix.exs, mix_helpers.exs
This addresses both #89 and #90.
On compile time, a warning is printed when the CPU platform is not supported.
On runtime, while loading the NIF, an error is printed. All NIF
stub functions now return stub values and do not call exit() so that
the integration keeps working (without doing anything) when running on
a non-supported OS.
@jeffkreeftmeijer can you test this somehow?
=> Don't crash when target platform is not supported

c_src/appsignal_extension.c, lib/appsignal/nif.ex, test/appsignal/nif_test.exs
Since #93, we can be in a state where the Nif is not loaded, but Appsignal is still running. For #81, we need a way for the diagnose Mix task to know wether or not the Nif was loaded properly. 
The most reliable way I could think of would be to implement `Appsignal.Nif.loaded?/0` as a function that returns `false` by default, but gets overwritten by the C code when the Nif loads successfully. @arjan @tombruijn wdyt?
=> Add Appsignal.Nif.loaded?/0

lib/appsignal/config.ex, test/appsignal/config_test.exs
Configure the path of the SSL certificate file. By default uses the
system's ca certificate files. Use this option to point to another
certificate file if there's a problem connecting to our API.
Only the agent does something with this config. So this looks fine for now?
Closes #97
=> Add ca_file_path config option

.travis.yml, config/config.exs, lib/appsignal/nif.ex, mix.exs, mix_helpers.exs, test/appsignal/config_test.exs, test/appsignal/nif_test.exs, test/appsignal/test_helper.exs, test/appsignal/utils/data_encoder_test.exs
=> Implement 'test_no_nif' test environment which skips the NIF

Makefile, c_src/appsignal_extension.c, mix_helpers.exs
And, don't declare the _data_to_json NIF function when we're not in
the test.
=> Pass 'TEST' define to .c source when compiling the NIF inside the tests

lib/appsignal/config.ex, test/appsignal/config_test.exs
Don't activate AppSignal always, when the push_api_key is in any config
type (system, app, env), but only activate AppSignal by default when the
push_api_key is found in the system environment variable
APPSIGNAL_PUSH_API_KEY.
This change makes the activation behavior the same for Elixir as for our
Ruby gem (https://github.com/appsignal/appsignal-ruby), which is more
flexible.
As discussed in https://github.com/appsignal/appsignal-elixir/issues/86
What this change means in practice. Before:
```
config :appsignal, :config,
name: :my_app,
push_api_key: "your-hex-appsignal-key"
```
This would make AppSignal active _always_, as long as the push_api_key
was set. The only exception was when `active` was explicitly set to
`false`.
After this change you need to explicitly set `active: true` to …
=> Auto activate when push_api_key in env, not always

lib/appsignal/utils/data_encoder.ex, test/appsignal/utils/data_encoder_test.exs
=> DataEncoder encodes bignums as strings

c_src/appsignal_extension.c, config/agent.exs, config/config.exs, lib/appsignal/nif.ex, lib/mix/tasks/appsignal.diagnose.ex, test/mix/tasks/appsignal_diagnose_test.exs, test/support/fake_nif.ex
Display whether or not the agent is running in a container in `mix appsignal.diagnose`.
=> :running_in_container in diagnose

lib/appsignal/config.ex, test/appsignal/config_test.exs
The active function seemed to be missing specs so I added them and added
a check if the config is valid as well. Same behavior as in the Ruby
gem.
https://github.com/appsignal/appsignal-ruby/blob/ca0a92e2c0f140d4cc9a014c3e47ac0582c5a67d/lib/appsignal/config.rb#L114-L116
The valid and active behavior was linked before on the push_api_key
presence, but that was changed in PR #119
=> Check valid state on Config.active?

lib/appsignal/config.ex, test/appsignal/config_test.exs
Ran into the issue that when name is undefined/`nil`, the name in
AppSignal.com would be `nil`. Something which I not at all suspected.
=> Allow app names to be strings

mix_helpers.exs
Closes #138. Needs a new version of the agent that includes a file named appsignal.version that holds the agent build's revision. 
TODO:
**Note**: this is a hotfix on master.
=> Check agent version in Mix.Appsignal.Helper.ensure_downloaded/1

lib/mix/tasks/appsignal.diagnose.ex
Appsignal.Mixfile.project isn't available during runtime, only at
compile time. The first time you would run `mix appsignal.diagnose` from
the package it would work if you ran `mix appsignal.diagnose` as the
very first thing after installing/compiling AppSignal.
By moving the "fetch version" call to a module attribute this value is
read at compile time and is available at runtime in that module
attribute.
Tested in a compiled Elixir app. Seems to work.
**Note: This is a fix on master**
=> Move package version to a module attribute

lib/appsignal.ex, lib/appsignal/config.ex, test/appsignal/config_test.exs
This allows the config to be initialized multiple times without setting
its options in environment variables. Currently, once the configuration
is written to the environment it its final. Because the environment
variables are leading in the configuration load order (see
http://docs.appsignal.com/elixir/configuration/load-order.html), they
cannot be overwritten once written to the environment.
This change allows us to initialize the config multiple times, without
writing it options to the environment immediately. This is useful for
non-application oriented code such as Mix tasks.
Based on #133
=> Write config to env only when needed

lib/appsignal/utils/tasks.ex
Add a module `:appsignal_tasks` that allows us to easily call mix tasks
in Elixir app releases. As inspired by
http://blog.plataformatec.com.br/2016/04/running-migration-in-an-exrm-release/
Usage:
```
_build/prod/rel/my_app/bin/my_app command appsignal_tasks diagnose|demo
```
**Note:** This doesn't fix the fact that the diagnose task will crash during its run, currently.
=> Make mix tasks available in releases

lib/appsignal/demo.ex, lib/appsignal/ecto.ex, lib/appsignal/phoenix/instrumenter.ex, lib/appsignal/phoenix/template_instrumenter.ex, test/appsignal/demo_test.exs, test/appsignal/transaction_test.exs, test/phoenix/instrumenter_test.exs
Follows this guide to name events:
http://docs.appsignal.com/api/event-names.html
The group names will become:
- phoenix_controller
- phoenix_template
- ecto
and were:
- phoenix
- render
- query
This allows users to more easily distinguish where what event is from.
=> Rename Phoenix framework event names

mix.exs
That fixes the crash in the diagnose task in production about missing
the app.
**Note**: Just one error remaining until the diagnose task actually works in a built app
=> Add HTTPoison app to mix.exs

lib/mix/tasks/appsignal.diagnose.ex, mix.exs
If we load `agent.ex` in the function it gets loaded at runtime, which
doesn't work for released apps.
Instead we load/compile the file first thing when compiling the
AppSignal package. Once it is loaded we set the data on the project's
data and make it accessible to the diagnose task through
`Mix.Project.config[:agent_version]`
Fixes #145
=> Load agent.ex only once and set on project data

mix.exs
As recommended by ex_doc in the README:
https://github.com/elixir-lang/ex_doc
What does runtime do?
`:runtime` - whether the dependency is part of runtime applications.
Defaults to true which automatically adds the application to the list of
apps that are started automatically and included in releases
Source: https://hexdocs.pm/mix/Mix.Tasks.Deps.html
=> Don't add ex_doc to runtime

lib/appsignal/config.ex, lib/mix/tasks/appsignal.install.ex, test/appsignal/config_test.exs, test/mix/tasks/appsignal_install_test.exs
Turns out that it wasn't meant to be used for app version, only git
commit SHA-s. Remove all the logic from the package, the AppSignal Rust
agent listens to this env var and manages the logic for us.
=> Remove revision logic

lib/mix/tasks/appsignal.install.ex, test/mix/tasks/appsignal_install_test.exs
Since removing the revision from the generated configuration file in
`config/appsignal.exs`, the install tasks adds an extra comma to the end
of the config file, which produces a syntax error:
** (Mix.Config.LoadError) could not load config config/appsignal.exs
** (TokenMissingError) config/appsignal.exs:5: syntax error: expression is incomplete
(elixir) lib/code.ex:170: Code.eval_string/3
(mix) lib/mix/config.ex:180: Mix.Config.read!/2
(mix) lib/mix/config.ex:217: anonymous fn/3 in Mix.Config.read_wildcard!/2
(elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
(stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
(stdlib) erl_eval.erl:878: :erl_eval.expr_list/6
This patch removes the extra comma.
=> Remove extra comma from generated config/appsignal.exs

agent.ex, lib/appsignal/nif.ex, lib/mix/tasks/appsignal.diagnose.ex, test/mix/tasks/appsignal_diagnose_test.exs
It's very difficult to capture the Nif STDOUT output using `ExUnit.capture_io`. Now we run the agent executable separately to capture the output.
Also force the `APPSIGNAL_ACTIVE` env to be true, otherwise it doesn't run properly -- Double check this, if we should do that or let the env config decide it. (That's how Ruby does it currently).
=> Force agent to run in diagnostics mode in diagnose

lib/mix/tasks/appsignal.install.ex, test/mix/tasks/appsignal_install_test.exs
Instead of activating AppSignal in the dev, prod and stag environments, we'll activate appsignal in config/appsignal.exs and deactivate it in config/test.exs (if it exists). Closes #155.
=> Activate AppSignal by default, deactivate in config/test.exs

lib/mix/tasks/appsignal.diagnose.ex, test/mix/tasks/appsignal_diagnose_test.exs
APPSIGNAL_ACTIVE=true isn't needed, because we directly call the agent
executable. It is needed in the Ruby gem because we don't directly call the executable and route the start through `Appsignal.start`
Added a test to make sure the agent still runs when the config has
`active: false`.
Follow up of #132
=> Update agent diagnostics logic in diagnose task

lib/mix/tasks/appsignal.install.ex, test/mix/tasks/appsignal_install_test.exs
APPSIGNAL_APP_ENV is a required key for env config, because we can't
detect the env at runtime.
=> Print APPSIGNAL_APP_ENV for env var config install

agent.ex, lib/appsignal/config.ex, lib/mix/tasks/appsignal.diagnose.ex, test/appsignal/config_test.exs
During a hot reload the AppSignal process is not reset/cleared/reloaded in any way to flush the previously set config env vars. When the AppSignal process starts it writes the current config to the environment so that the agent can read from this and be initialized with the same config.
During a hot reload the AppSignal process tries to initialize the config again, but because the system env still contains the config for the agent from the last time it initialized the config it reads the previous config. The env vars are loading in initializing the config, as
described here: http://docs.appsignal.com/elixir/configuration/load-order.html
The fix? Underscore all the config sent to the agent process so that it doesn't conflict with the application's config.
**Note:** Requires the agent to be …
=> Configure agent with underscored config env vars

mix.exs
We're currently depending on Phoenix ~> 1.2.0, which matches all 1.2.x
versions, but not 1.3.0.
Instead, we're now depending on >= 1.2.0, which includes all versions
above 1.2.0 (including 1.3.x and 2.x), but no prereleases. This way, we
can make sure Phoenix support works in the prerelease versions, and we
won't have to bump the Phoenix dependency when a new release comes out.
https://hexdocs.pm/elixir/Version.html
=> Depend on Phoenix >= 1.2.0 instead of ~> 1.2.0

lib/appsignal/phoenix.ex, lib/appsignal/phoenix/instrumenter.ex, lib/appsignal/transaction.ex, test/phoenix/instrumenter_test.exs, test/phoenix/phoenix_test.exs, test/support/fake_transaction.ex
Instead of calling `try_set_action/1` in `submit_http_error/5`, where
the `:phoenix_controller` and `:phoenix_action` keys are not present in
the conn, we'll set the action name in `phoenix_controller_call/3`.
`phoenix_controller_call(:start, _, %{conn: conn})` is immediately
called after setting the controller and action keys
(https://github.com/phoenixframework/phoenix/blob/2f475135b8ee5e4cbbd7b6e616ad6eb91e04c3fa/lib/phoenix/controller/pipeline.ex#L26-L28), and is triggered before exceptions
in the controller happen.
Closes #11.
=> Call Transaction.try_set_action/1 in phoenix_controller_call/3

mix_helpers.exs
When the installation is being run under the root user tar does not use
the `--no-same-owner` option by default. As described in the "tar" docs:
"--no-same-owner extract files as yourself (default for ordinary users)"
Root is not an ordinary user and thus this is not an option.
The problem then is that it tries to apply the same permissions as the
files that were packed, causing errors because those user ids don't
necessarily exist on a user's machine. And if they do it's unlikely that
they are from the user we want.
I was able to reproduce this with a Docker dingy setup as described in
issue #168: https://github.com/appsignal/appsignal-elixir/issues/168
Fixes #168
=> Fix unpacking agent tar as root

lib/appsignal/instrumentation/helpers.ex, test/appsignal/instrumentation/helpers_test.exs
Fixes #174.
Remove the %Plug.Conn{} clause of Instrumentation.Helpers.instrument/5, add Instrumentation.Helpers.instrument/3 instead, which can be called without passing a Transaction. A usage example of this can be found in [the instrumentation branch in appsignal-phoenix-example](https://github.com/jeffkreeftmeijer/appsignal-phoenix-example/blob/instrumentation/web/controllers/page_controller.ex#L19-L27).
=> Remove the %Plug.Conn{} clause of Instrumentation.Helpers.instrument/5

lib/appsignal/backtrace.ex, lib/appsignal/error_handler.ex, lib/appsignal/transaction.ex, test/appsignal/backtrace_test.exs, test/appsignal/transaction_test.exs
Backtrace removes backtrace entries with an argument list, and formats the remaining lines. Closes #182.
=> Add `Backtrace.from_stacktrace` to format `System.stacktrace`

lib/appsignal/error_handler.ex, lib/appsignal/phoenix.ex, lib/appsignal/phoenix/plug.ex, test/appsignal/error_handler/error_extracter_test.exs, test/appsignal/error_handler/error_matcher_test.exs, test/phoenix/phoenix_test.exs, test/phoenix/plug_test.exs
Instead of rescuing from exceptions and re-raising them using a rescue
block, this switches it over to a catch block, which uses
`Plug.ErrorHandler.__catch__/4` to re-raise the error. This allows us to
catch errors caused by crashing processes (like the timeout in the added
test).
This can be merged on its own, but not released without #190, as that could cause duplicate errors to be registered.
=> Catch errors caught by Plug.ErrorHandler

lib/appsignal/error_handler.ex, test/appsignal/error_handler/error_matcher_test.exs, test/appsignal/error_handler_test.exs
This is a continuation of #190, which was closed but can’t be reopened because the branch was rebased.
Closes #157 & #173.
Before, the ErrorHandler had to match on :error events (besides
:error_report events) to be able to catch errors that were already
caught by Plug.ErrorHandler.
After merging #187, we can drop support for :error events. This drops
support for unsupervised "bare" spawns, and only triggers an error when
a process actually crashes. Also, this removes a lot of code that dealt
with not sending error reports twice (after the :error event and the
:error_report event).
=> Don't handle :error events in ErrorHandler

.gitignore, mix.exs, mix_helpers.exs
When testing the Elixir integration, using the agent repository, you can
now use a local agent build.
Use the `rake integrations:install` task in the agent repository to
install the agent and extension to the local integrations, the Ruby gem
and Elixir package.
With this change the Elixir package will pick up the local agent version
and install that rather than pull the latest version from the agent CDN.
Do make sure you remove the local files from the `c_ext` directory when
you want to use a proper released version again.
Depends on PR in Agent repo: https://github.com/appsignal/appsignal-agent/pull/244
Closes #156
=> Allow local agent releases to be used

lib/appsignal/instrumentation/helpers.ex, test/appsignal/instrumentation/helpers_test.exs
This change allows calls to `Appsignal.Instrumentation.Helpers.instrument/6` with `nil` as an argument. In a way, it tries to make `instrument/6` consistent with `instrument/3` when no transaction is found for the current process.
This helps avoiding clauses or conditionals in instrumented code. For example:
```elixir
defmodule HelloServer do
use GenServer
def handle_call({:hello, name, transaction}, _from, state) do
instrument(transaction, "hello", "Handling hello request", fn ->
{:reply, do_hello(name), state}
end)
end
def handle_call({:hello, name, nil}, _from, state) do
{:reply, do_hello(name), state}
end
defp do_hello(name) do
"Hello, #{name}!"
end
end
```
With this patch the second clause for `handle_call/3` can be dropped.
We ran into this issue in a production app where we need to …
=> Allow nil transactions

lib/appsignal/phoenix/channel.ex, lib/appsignal/transaction.ex, test/phoenix/channel_test.exs
Closes #194.
Instead of using the :background_job namespace,
Appsignal.Phoenix.Channel will use :channels instead. This also allows
users to set their own custom namespaces in
Appsignal.Transaction.start/2.
=> Use :channels namespace in Appsignal.Phoenix.Channel

agent.ex, c_src/appsignal_extension.c, lib/appsignal/nif.ex, lib/mix/tasks/appsignal.diagnose.ex, mix.exs, test/appsignal/release_upgrade_test.exs, test/mix/tasks/appsignal_diagnose_test.exs, test/support/fake_nif.ex
The extension returns a JSON object, as a string, which contains the
agent diagnostics report.
The report definition is defined in the diagnose CLI task so we can
check all the tests and display them in a human readable format.
This change makes it possible to return the agent diagnostics report
without capturing the STDOUT while the agent is running. This proved
difficult to do in Elixir, where we previously called the agent
executable directly.
Instead of printing the report to STDOUT the extension will now return
the report as a JSON object, which is formatted as a string which needs
to be parsed into JSON first.
This report may be incomplete when the agent fails to start or something
else goes wrong. Any error will be captured and added to the agent
report.
Depends on #195
=> Parse new report from agent diagnose mode

lib/appsignal/transaction.ex, test/appsignal/appsignal_test.exs, test/appsignal/config_test.exs, test/appsignal/release_upgrade_test.exs, test/appsignal/system_test.exs, test/appsignal/transaction/filter_test.exs, test/appsignal/transaction_test.exs, test/mix/tasks/appsignal_diagnose_test.exs, test/mix/tasks/appsignal_install_test.exs, test/support/utils.ex
Instead of calling `System.put_env` and `Application.put_env` all over the test suite, there are now a couple of helpers that update the system environment or application configuration, run a function, and put them back. This removes all occurrences of `System.put_env` and `Application.put_env` from the test suite, outside of the newly added helpers.
=> Add `with_config` and `with_env` for testing purposes

config/config.exs, lib/appsignal/config.ex, lib/appsignal/diagnose/agent.ex, lib/appsignal/diagnose/host.ex, lib/appsignal/diagnose/library.ex, lib/appsignal/diagnose/paths.ex, lib/appsignal/diagnose/report.ex, lib/appsignal/diagnose/validation.ex, lib/mix/tasks/appsignal.diagnose.ex, test/appsignal/config_test.exs, test/appsignal/diagnose/report_test.exs, test/mix/tasks/appsignal_diagnose_test.exs, test/support/fake_diagnose_report.ex
This change will allow users to send the diagnostics report to
AppSignal. We'll ask before sending if the user wants this, but because
we see how useful this can be when debugging an issue it sends the
report by default. When you press enter, no input, "Y" (yes) is
submitted.
Why this change?
We've seen that in every support request we get we'll ask for the
diagnostics report. To make it easier for everyone this change allows
users to send it directly to AppSignal so our support team can review it
without valuable data getting lost by formatting by our support system
for example.
We also provide the user with a support token when they send the report.
This can be useful for a user if they see a problem with the output and
want to dive right in with the report. They can contact us with the …
=> Send diagnostics data report to AppSignal

lib/appsignal/error_handler.ex, test/appsignal/error_handler/error_extracter_test.exs
When an error is triggered from a Task, or another linked process:
Task.async(fn ->
raise("Exception")
end)
The error looks like this:
{
%RuntimeError{message: "Exception!"},
[
{AppsignalPhoenixExample.PageController, :"-exception/2-fun-0-", 0, [file: 'web/controllers/page_controller.ex', line: 18]},
{Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 85]},
{Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 36]},
{:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}
]
}
Appsignal.ErrorHandler.extract_reason_and_message/2 currectly returns
"%RuntimeError{message: "Exception!"}" as the name, and includes the
whole stacktrace in the description.
This patch changes the name to "RuntimeError", and the description to
"Process #PID<0.574.0> …
=> ErrorHandler handles errors in tuples

lib/mix/tasks/appsignal.install.ex, test/mix/tasks/appsignal_install_test.exs
While setting up AS, I ran `mix appsignal.install your-push-api-key` and was a bit confused why my app was running in `dev` while deployed, but that's the default env.
Looking at the docs, `env: Mix.env` is listed in the [example config](http://docs.appsignal.com/elixir/installation.html#configuration), so after adding that to my `config.exs`, everything was smooth sailing. So I made this pull because I'm guessing a lot of people will use the mix task and probably think 'that's it'. 
I'm not sure if this was done intentionally, because [http://docs.appsignal.com/elixir/configuration/](http://docs.appsignal.com/elixir/configuration/) does mention `env` in in the minimal required config, and in the example to set up `prod.exs` manually:
```
config :appsignal, :config,
active: true,
env: …
```
=> Set `env: Mix.env` in generated config.exs

lib/appsignal/phoenix/template_instrumenter.ex
I've noticed that slow events report groups template render events from multiple controllers. That's not expected and I'd like to see event response time separately.
=> phoenix template: use path as title instead of name

test/appsignal/config_test.exs, test/appsignal/diagnose/report_test.exs, test/appsignal/release_upgrade_test.exs, test/mix/tasks/appsignal_install_test.exs
To help prevent future debug sessions, such as the one for our nominee
for most obscure bug of the year, we are going to use more explicit app
names that can be easily traced back to the Elixir package test suite.
=> Use more explicit app name in test suite

lib/mix/tasks/appsignal.install.ex, test/mix/tasks/appsignal_install_test.exs
dace2aa0df7d63a09a4000e6617b2b11201132f6 introduced a regression where the main config (`config/appsignal.exs`) overwrote the `active` option in the environment based configuration, because the main config is loaded after the environment config. 
Instead of setting `active` to `true` in the main configuration and disabling it in the test environment, we're now only setting the `active` configuration in the main config if no env-based configuration files exist. 
Thanks for reporting this issue, @bittersweet! 🥇
=> Only set `active` in appsignal.exs if no environment based configuration files exist

lib/appsignal.ex, lib/appsignal/transaction/registry.ex, test/appsignal/appsignal_test.exs, test/appsignal/transaction/registry_test.exs
Hi,
I'll start with a short background story so you can have a context of why this change is important.
We use quite a few partials in our project to render relatively big collections (100-500 items). Template rendering was taking up to 50% of time on such pages according to performance reports. 
We started adding more instrumentation to views in a mission to narrow down the bottleneck. This resulted in a noticeable increase of render time. We also saw performance reports pointing that the issue was in rather view helpers doing simple operations on small lists.
We used Benchfella to verify the issue with these view helpers and quickly discovered that it was caused by Appsignal decorated functions being invoked in a loop. Benchmarking further only Appsignal instrumentation we pinned the …
=> Improve registry lookup performance

agent.ex, c_src/appsignal_extension.c, config/config.exs, lib/appsignal/config.ex, lib/appsignal/diagnose/agent.ex, lib/appsignal/diagnose/host.ex, lib/appsignal/diagnose/library.ex, lib/appsignal/diagnose/paths.ex, lib/appsignal/diagnose/report.ex, lib/appsignal/diagnose/validation.ex, lib/appsignal/error_handler.ex, lib/appsignal/nif.ex, lib/appsignal/phoenix/channel.ex, lib/appsignal/transaction.ex, lib/mix/tasks/appsignal.diagnose.ex, mix.exs, test/appsignal/config_test.exs, test/appsignal/diagnose/report_test.exs, test/appsignal/error_handler/error_matcher_test.exs, test/mix/tasks/appsignal_diagnose_test.exs, test/phoenix/channel_test.exs, test/support/fake_diagnose_report.ex, test/support/fake_nif.ex
Adds `ErrorHandler.extract_stacktrace/1`, which tries to extract the stacktrace from the exception, as that stack trace will include the line the error happened on as opposed to the stack trace from the error report's `:error_info`, which does not.
In short (and as shown in 2a5bf34c20aa6b4051b055fda0d6bab2ab562c06):
```
(stdlib) gen_server.erl:812: :gen_server.terminate/7
(stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```
... becomes:
```
(elixir) unicode/unicode.ex:190: String.Unicode.length/1
test/appsignal/error_handler/error_matcher_test.exs:27: Appsignal.ErrorHandler.ErrorMatcherTest.CrashingGenServer.handle_info/2
(stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
(stdlib) gen_server.erl:667: :gen_server.handle_msg/5
(stdlib) proc_lib.erl:247: …
```
=> Better backtraces for linked processes

agent.ex, lib/appsignal/config.ex, test/appsignal/config_test.exs
Agent bumped to support `_APPSIGNAL_DNS_SERVERS` configuration option.
Tracking issue: https://github.com/appsignal/appsignal-agent/issues/246
=> Add DNS servers configuration option

mix_helpers.exs
Closes #223
It can happen that curl is not installed on the system. If this is the
case, print an error that the agent could not be installed.
This to improve the normal error message which doesn't help the user
figure out what's going wrong.
```
** (ErlangError) erlang error: :enoent
(elixir) lib/system.ex:552: System.cmd("curl", {options...})
mix_helpers.exs:80: Mix.Appsignal.Helper.download_file/2
{stacktrace...}
```
=> Check if curl is installed before calling it

lib/appsignal/config.ex, test/appsignal/config_test.exs
Related PR https://github.com/appsignal/appsignal-ruby/pull/312.
This feature was added to the AppSignal extension in PR
https://github.com/appsignal/appsignal-agent/pull/255, this PR adds the
config option to the Elixir package.
Configure `ignore_namespaces` to ignore transactions (requests and jobs)
from certain namespaces configured as described in our docs:
http://docs.appsignal.com/application/namespaces.html
This allows users to ignore entire namespaces, such as administration
panels, without having to ignore all the controllers in that namespace
with `ignore_actions`.
=> Add ignore_namespaces option

mix_helpers.exs
Could you do a sanity check @jeffkreeftmeijer ?
And should I added mapping for the other linux archs too?
```
x86_64-redhat-linux-gnu
x86_64-alpine-linux
x86_64-unknown-linux
```
As reported in https://app.intercom.io/a/apps/yzor8gyw/respond/inbox/540709/conversations/10344463255
**Note**: This is a PR aimed at master so we can do a patch release
=> Add arch mapping for 32bit linux

mix_helpers.exs
This to fix potential issues with the tmp dir not existing, such as on
Microsoft Windows, but also on machines where the tmp dir is not
writable.
Hopefully this fixes a potential permission issues as described in #213.
Replacement of #216
=> Download agent in dynamic tmp path

lib/appsignal.ex, lib/appsignal/error_handler.ex, lib/appsignal/phoenix.ex, lib/appsignal/phoenix/instrumenter.ex, lib/appsignal/phoenix/plug.ex, lib/appsignal/plug.ex, lib/appsignal/transaction.ex, mix.exs, test/appsignal/appsignal_test.exs, test/appsignal/plug_test.exs, test/phoenix/instrumenter_test.exs, test/support/fake_transaction.ex
Closes #153.
Adds `Appsignal.Plug`, which handles instrumentation and error handling for Plug apps (including Phoenix). Deprecates most of `Appsignal.Phoenix` and `Appsignal.Phoenix.Plug`.
=> Plug support without Phoenix

lib/appsignal/nif.ex
As reported in #165, Dialyzer produced a warning in Phoenix and Plug
applications:
lib/hue_labs_backend/endpoint.ex:51: The pattern 'true' can never match the type 'false'
lib/hue_labs_backend/endpoint.ex:51: The test 'nil' | 'no_sample' == 'sample' can never evaluate to 'true'
Normally, the agent will decide which of the samples sent to it require request
metadata, by returning either `:sample` or `:no_sample` from
`Appsignal.Nif._finish/1`. By default (and when the NIF can't be
loaded), `_finish/1` will return `:no_sample`, which is hardcoded in the
function in the `Appsignal.Nif` module. The function in the NIF itself
will overwrite the function in the Elixir code when the NIF is loaded.
Dialyzer can't seem to handle extending code like this, and will assume
that `_finish/1` will …
=> Trick Dialyzer into not warning

.travis.yml, lib/appsignal/error_handler.ex, test/appsignal/error_handler/error_matcher_test.exs
Use :gen_event instead of GenEvent, which is deprecated, and is [breaking the build](https://travis-ci.org/appsignal/appsignal-elixir/jobs/266830270) on 1.5.
=> Drop GenEvent

lib/appsignal/instrumentation/decorators.ex, lib/appsignal/phoenix/channel.ex, lib/appsignal/transaction.ex, test/appsignal/instrumentation/decorator_test.exs, test/phoenix/channel_test.exs, test/support/fake_transaction.ex
Closes #243 and #232.
Adds `Appsignal.Phoenix.Channel.channel_action/5`, which takes the action's params, sanitises them, and sends them along with the sample. It's also used in the `channel_action/2` decorator.
- Removes dependency on the `Mock` library in channel tests, and uses `FakeTransaction` instead.
- Deprecates `Appsignal.Channel.set_metadata/1`as `channel_action/5` now makes sure to set the metadata (like we do in `Appsignal.Plug`).
- Cleans up `Appsignal.Phoenix.Channel` tests
=> Channel params

lib/appsignal/instrumentation/decorators.ex, test/phoenix/channel_test.exs
Since 0ab1e198f4e8b99d114f7098a7eb34f339091655,
Appsignal.Instrumentation.Decorators.channel_action/2 uses
Appsignal.Phoenix.Channel.channel_action/5 to add the payload to the
transaction as params. Since this doesn't work when the payload is
unbound, this patch adds a fallback to channel_action/4.
=> Don't crash with unbound channel payloads

mix_helpers.exs
As of 2017-09-13, the elixir:*-alpine Docker images are returning `:erlang.system_info(:system_architecture)` as `x86_64-pc-linux-musl ` instead of `x86_64-unknown-linux-gnu`.
There seems to be no change in the images themselves (https://github.com/c0b/docker-elixir/commits), but all of them have just been updated (https://hub.docker.com/r/library/elixir/tags/). I suspect this was the change in the underlying erlang:*-alpine images: https://github.com/c0b/docker-erlang-otp/commit/e7d145c915458e5bbb857a57c9aad7125f95a853
=> Add architecture for elixir:alpine Docker image

lib/appsignal/instrumentation/decorators.ex, lib/appsignal/phoenix/channel.ex, test/phoenix/channel_test.exs
Due to the structure of the decorators, we can't handle unbound
parameters in the channel_action decorator. To make sure we don't break
compilation for apps that don't bind all parameters, we've disabled
sending parameters in the `channel_action` decorator.
To include parameters, please use
`Appsignal.Phoenix.Channel.channel_action/5` directly:
defmodule PhoenixChatExampleWeb.RoomChannel do
use Phoenix.Channel
import Appsignal.Phoenix.Channel, only: [channel_action: 5]
def handle_in("new_msg" = action, payload, socket) do
channel_action(__MODULE__, action, socket, payload, fn ->
broadcast! socket, "new_msg", %{body: 'body'}
{:noreply, assign(socket, :user_id, 4)}
end)
end
end
=> No channel payloads in the channel_action decorator

lib/appsignal.ex, test/appsignal/appsignal_test.exs, test/phoenix/phoenix_test.exs
Before this change calling send error multiple times in the same process would only post an error once because the submitted transaction was still around.
=> Remove transaction from registry in send error

lib/appsignal.ex, mix.exs
This is mostly to link to the install guide from the Hex docs. After this patch, the documentation index is https://hexdocs.pm/appsignal/Appsignal.html#content instead of https://hexdocs.pm/appsignal/api-reference.html, and there's a quick note of the install guide.
=> Show Appsignal as doc index, mention install guide

mix_helpers.exs
This allows us to ship separate agent builds for GNU and musl builds.
Hopefully solving the DNS timeouts issue for good:
https://docs.appsignal.com/support/known-issues.html#dns-timeouts
The musl-compatible agent can be force installed with the
`APPSIGNAL_BUILD_FOR_MUSL` environment variable.
Override with `export APPSIGNAL_BUILD_FOR_MUSL=1` before calling `mix
{task}` if this doesn't work automatically.
This to prevent it from downloading an empty string and returning a less
than helpful error message about a failed download.
---
Also fixes #258 
Part of https://github.com/appsignal/appsignal-agent/pull/286 (private link)
=> Add specific musl host triple architecture

agent.ex, mix_helpers.exs
A new FreeBSD package to support FreeBSD hosts was added in commit
b9546ca, but no architecture mapping
was present in our mix helpers yet.
Based on #265 
Part of https://github.com/appsignal/appsignal-agent/issues/175
=> Map FreeBSD target triples

lib/appsignal/config.ex
We would like to configure `env` via ENV var. We also use [distillery](https://github.com/bitwalker/distillery) for the release and it doesn't support Dynamic code.
https://hexdocs.pm/distillery/getting-started.html#application-configuration
So you can't do `env: System.get_env("APP_SIGNAL_ENV") |> String.to_atom`.
The PR just allows binary (String) to be given as configuration parameters.
=> Support ENV var with distillery config

lib/appsignal.ex, lib/appsignal/diagnose/logs.ex, lib/appsignal/nif.ex, lib/mix/tasks/appsignal.diagnose.ex, test/mix/tasks/appsignal_diagnose_test.exs
Closes #273.
Instead of using `:logger` from `Appsignal.Nif`'s on_load, we append to a file (install.log) using the `File` module, and print a message when the app starts without the nif being loaded. We'll include install.log in the diagnose output.
=> Don't use :logger from @on_load

test/appsignal/plug_test.exs, test/mix/tasks/appsignal_diagnose_test.exs, test/mix/tasks/appsignal_install_test.exs, test/phoenix/channel_test.exs, test/phoenix/instrumenter_test.exs, test/phoenix/phoenix_test.exs, test/support/fake_demo.ex, test/support/fake_diagnose_report.ex, test/support/fake_nif.ex, test/support/fake_system.ex, test/support/fake_transaction.ex, test/support/test_agent.ex
Instead of relying on the agent names, this patch uses pids whenever possible to prevent random test failures caused by tests terminating each other's agents.
=> Add TestAgent, pass test agent pids explicitly

config/config.exs, lib/appsignal/diagnose/library.ex, lib/appsignal/system.ex, lib/mix/tasks/appsignal.diagnose.ex, mix.exs, mix_helpers.exs, test/appsignal/system_test.exs, test/appsignal/test_helper.exs, test/mix/tasks/appsignal_diagnose_test.exs, test/support/fake_os.ex, test/support/fake_system.ex, test/support/utils.ex
With the AppSignal for Elixir package v1.4.0 release we dropped support
for some older Operating Systems that use a libc version older than
2.12.
Since package v0.11.0 we started using a musl build so the libc version
didn't matter on the user's machine. Before that we used a very old
machine that used the libc version from CentOS 5, so we supported some
very old systems.
To now support older Operating System versions, with a libc older than
2.12, this change adds a check for the older versions and selects the
musl build instead.
This should fix the problem for people upgrading to (future) package
1.4.1 and higher.
Also move the build detection to the System module so we can reuse the
logic and add specs for its behavior.
- how would that work in a release binary? Seems to work
=> 🐞Use musl build for older systems

test/appsignal/system_test.exs, test/support/fake_os.ex
Use the new `TestAgent` module, which has logic to make sure the process exits after the test is done, to build `FakeOS`.
=> Convert FakeOS to a TestAgent

lib/appsignal/error_handler.ex, test/appsignal/error_handler/error_matcher_test.exs, test/appsignal/plug_test.exs
Tested this in the plug_test by raising the wrapped error. We couldn't
find a way to raise the unwrapped error, e.g. `nil.undefined_function`
and make the test pass.
Closes #245.
=> ErrorHandler unwraps Plug.Conn.WrapperError

lib/appsignal/plug.ex, test/appsignal/plug_test.exs
Since the request_id hasn't been set when the Transaction gets started
in `Appsignal.Plug.call/2`, the previous implementation never actually
found the current request's ID.
This patch generates a Transaction ID and adds the reuqest ID to the
metadata later when extracting the metadata from the conn. This causes
the Transaction ID to be different than the request ID in the metadata,
so we don't rely on the processor falling back to the transaction ID
when no request ID is set.
Closes #282.
=> Fetch request_id in Appsignal.Plug.extract_meta_data/1

lib/mix/tasks/appsignal.diagnose.ex
As reported via [support](https://app.intercom.io/a/apps/yzor8gyw/respond/inbox/search/conversations/13531351818?q=parker&tag=0) (private Intercom link)
When running the diagnose task from a release build, the appsignal
configuration is not loaded until the appsignal application is started.
This caused incorrect configuration in diagnose reports.
=> Ensure the appsignal application is started when running diagnose

lib/appsignal/plug.ex, test/appsignal/plug_test.exs
Closes #285.
As explained in #285, relying on `Plug.ErrorHandler.__catch__/4` causes exceptions to not be reported if the response is already sent. This patch removes this issue by calling `Exception.normalize/3` from the `call/2` wrapper and reraising the error using `:erlang.raise/3`.
@schnittchen, if you have time, could you try this branch out locally to see if it solves your issue? We'll do some more testing ourselves to make sure everything keeps working properly.
=> Don't use Plug.ErrorHandler.__catch__/4 in Appsignal.Plug

.travis.yml, lib/appsignal/system.ex
I thought I might be able to get the ball rolling on Elixir 1.6 support.  This PR adds Elixir 1.6.0 as a build target, and addresses the compilation errors in #296 which are the result of this manifest directory consolidation: elixir-lang/elixir@d941fe0
Please note, this does not make the lib totally ready for primetime on 1.6. Given a few test regressions, I added `elixir: 1.6.0` to the `allow_failures:` list for now.
Not sure if this would really be considered a "bugfix", so let me know if I should open this PR on a different branch.
=> Fix compile errors on Elixir 1.6

lib/appsignal/utils/data_encoder.ex, test/appsignal/utils/data_encoder_test.exs
When given a list with a cons operator, an improper list, the DataEncoder has some trouble
encoding the value, instead giving the following error for this test:
```
1) test encode a list a cons operator (Appsignal.Utils.DataEncoderTest)
test/appsignal/utils/data_encoder_test.exs:101
** (FunctionClauseError) no function clause matching in Enum."-each/2-lists^foreach/1-0-"/2
The following arguments were given to Enum."-each/2-lists^foreach/1-0-"/2:
#Function<1.110451145/1 in Appsignal.Utils.DataEncoder.encode/1>
"foo"
code: resource = DataEncoder.encode(["" | "foo"])
stacktrace:
(elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
(elixir) lib/enum.ex:675: Enum.each/2
(appsignal) lib/appsignal/utils/data_encoder.ex:21: Appsignal.Utils.DataEncoder.encode/1 …
```
=> 🐞 Fix DataEncoder.encode error

lib/appsignal/error_handler.ex, test/appsignal/error_handler_test.exs
Closes #302.
When `Appsignal.send_error/6` is called the transaction found using
`Transaction.lookup/0` will never be the transaction for
`Appsignal.send_error/6`. It's removed from the `TransactionRegistery`
before `Appsignal.ErrorHandler.submit_transaction/6` will handle the
error.
Since we have the transaction available in
`Appsignal.ErrorHandler.submit_transaction/6`, let's just pass the given
transaction and avoid a broken lookup for `Appsignal.send_error`.
As reported in: https://app.intercom.io/a/apps/yzor8gyw/respond/inbox/unassigned/conversations/14370088531
=> Fix transaction metadata for send_error

lib/mix/tasks/appsignal.diagnose.ex
Part of #295.
Instead of starting the whole app, the configuration is loaded when
using `Application.load/1`. This patch uses that over
`Application.ensure_all_started` to keep the lock file from being
stolen.
=> Use Application.load/1 in diagnose task

lib/appsignal/plug.ex, test/appsignal/plug_test.exs, test/support/fake_transaction.ex
Closes #307.
As explained in the original issue, wrapping the `call/2` function in an endpoint takes the `Plug.Conn` *before* the request is executed. This is a regression introduced in #287, because we stopped using`Plug.Conn.ErrorHandler.__catch__/4`, which took care of taking the updated conn out of `Plug.Conn.WrapperErrors`.
=> Take the Plug.Conn from Plug.Conn.WrapperErrors

lib/agent.ex
- Fix locking issue on diagnose mode run.
- Increase stored length of error messages.
These changes are currently being tested in Ruby gem 2.5.1.beta.1. This PR serves to merge the same changes into the Elixir package.
=> ⌨️ Bump agent to ee63235

lib/appsignal/plug.ex, test/appsignal/plug_test.exs, test/support/fake_transaction.ex
Previously, `Appsignal.Plug` used the method and the path as the action name in plug-only apps. This caused problems for apps with unique URLs, as it creates a seperate performance/error incident for each variation of the URL. To fix this, we're using "unknown" as the default action name in Plug apps, and we're allowing users to override that by using `Appsignal.Transaction.set_action/1-2`:
```elixir
get "/users/:id" do
Appsignal.Transaction.set_action("GET /users/:id")
send_resp(conn, 200, "Welcome")
end
```
=> Use "unknown" as action for Plug-only transactions, set action before `call/2`

.travis.yml
Currently the only OTP version it randomly fails on to test the agent in
diagnose mode. Outside the test env this seems to work fine. Given
enough retries or luck it will eventually work on TravisCI, but it's not
helpful to developers continuously seeing a red mark for build status.
=> Allow OTP 18.3 failures

.travis.yml, lib/appsignal/backtrace.ex, test/appsignal/backtrace_test.exs, test/appsignal/error_handler/error_matcher_test.exs
Closes #325.
Instead of taking off the first backtrace line to make sure no function arguments end up in the backtrace, this patch replaces the argument list with the function arity, turning it into a "normal" backtrace line. Also, the test uses `Float.ceil` to trigger a badarg error instead of `String.length`, because the latter has different implementations on different Elixir versions (which makes it harder to assert stacktraces).
This patch fixes the test failures we've been seeing on Elixir 1.6, so it removes 1.6 from the allowed failures list in the Travis config.
=> ⌨️ Filter arguments in backtraces

lib/appsignal/demo.ex, lib/appsignal/transaction.ex, test/appsignal/demo_test.exs, test/appsignal/transaction_test.exs, test/support/fake_demo.ex
Part of #299.
Explicitly remove completed Transactions from the TransactionRegistry instead of waiting for a Transaction's process to go DOWN. For convenience, `Demo.create_transaction_(error|performance)_request` now returns the transaction object, because it'll be removed before it reaches the test.
=> Remove transaction when calling `Transaction.complete`

lib/appsignal/transaction.ex, lib/appsignal/transaction/registry.ex, test/appsignal/transaction/registry_test.exs
Back when we handled `:error` reports from `:error_logger` (which was removed in #193), we had to explicitly make sure errors weren't being sent twice by replacing transactions in ets with a `:removed` atom. This was to make sure an error from the then-Phoenix Plug, wouldn't be sent again after being caught by Erlang's error logger.
Because we only handle crashes now, that's no longer the case, so we can immediately hard-remove transactions when they're completed. We do, however, keep a timeout when a process registered in ets goes DOWN, to wait for an `error_report`, to come in before removing the transaction.
=> Hard-remove transactions from the Registry

lib/appsignal.ex, lib/appsignal/nif.ex, lib/appsignal/transaction.ex, test/appsignal/appsignal_test.exs, test/appsignal/nif_test.exs, test/appsignal/transaction_test.exs, test/support/utils.ex
For `Appsignal.send_error/7`, we need a Transaction to put the error in, but we don't need to register the created transaction in the `TransactionRegistry`/
Before, there was no way to create a Transaction without registering it. This patch adds `Transaction.create/2` which creates a Transaction with a resource, but doesn't register it, which is then used by `Appsignal.send_error/7`.
=> Don't register Transactions created by `Appsignal.send_error/7`

agent.exs, c_src/appsignal_extension.c, lib/appsignal.ex, lib/appsignal/nif.ex, test/appsignal/appsignal_test.exs
Add 3rd argument to metric functions to accept tags.
* add tags to `set_gauge`
* add tags to `increment_counter`
* add tags to `add_distribution_value`
=> Accept tags for (custom) metrics

lib/appsignal/config.ex, test/appsignal/config_test.exs
It is unused in the extension as it's filtered in the Elixir package
already. The extension ignores this config option, so let's remove it.
=> Remove filter_parameters config for extension

lib/appsignal/transaction/registry.ex, test/appsignal/transaction/registry_test.exs
Closes #299.
*Note*: this is based on #332. 
Currently, we wait for process monitors to be removed automatically when the monitored process goes DOWN. This can be a problem for long-running processes, as the monitors are not removed from the registry.
This patch adds the monitor reference to the registry and makes sure the process gets demonitored when the transaction is completed.
=> Demonitor processes when the transaction completes

agent.exs, lib/appsignal/config.ex, lib/appsignal/system.ex, test/appsignal/config_test.exs, test/appsignal/diagnose/report_test.exs, test/appsignal/release_upgrade_test.exs, test/appsignal/system_test.exs, test/support/fake_system.ex
Instead we'll base determine this default as a fallback in the
extension. The integrations don't need to know about the default
hostname, also reduces the logic in the integrations.
The integrations will only set the hostname config option in the
environment `_APPSIGNAL_HOSTNAME` when it has been configured in the
app. If not, it will set an empty string, which is interpreted as an
empty value by the extension.
Depends on https://github.com/appsignal/appsignal-agent/pull/335
🚨  Needs an agent release before merging! 🚨
=> Remove default hostname

lib/appsignal.ex, lib/appsignal/config.ex, test/appsignal/config_test.exs
Closes #335. Thanks for reporting this, @axelson!
If AppSignal is not active, we'll :info-log the "AppSignal disabled"
line. This will show in a Phoenix app in development, but not in tests
(as the default :logger level for tests is :warn in Phoenix).
We'll only warn if the configuration is invalid, but AppSignal was set
to active (like when omitting the push_api_key from
config/appsignal.exs).
=> Log with :info level instead of :warn when AppSignal is disabled

lib/appsignal/config.ex, lib/mix/tasks/appsignal.install.ex, test/mix/tasks/appsignal_install_test.exs
Adds an explicit header whitelist to the configuration file or environment variables created/suggested by the installer. Closes #317.
*Note*: This is a work in progress until we've decided on the final list of default headers.
=> Explicit header whitelist in configuration

lib/appsignal/config.ex, lib/appsignal/plug.ex, lib/mix/tasks/appsignal.install.ex, test/appsignal/config_test.exs, test/appsignal/plug_test.exs, test/mix/tasks/appsignal_install_test.exs
Instead replace fallback header list with the new default.
Remove the warning that's printed after upgrade and the option is not
set.
Don't add it to the config by default, but allow complete overrides of
the config option.
Conclusion: use saner defaults, don't require users to do anything to
their configuration.
If they miss any headers they can update the configuration after
upgrade. This requires a smaller segment of our users to update their
config manually.
Description copied from https://github.com/appsignal/appsignal-ruby/pull/410
=> Don't suggest request headers on install, replace fallback header list

lib/appsignal/utils/params_filter.ex, test/appsignal/transaction/filter_test.exs
=> Merge instead of ignore Phoenix's :filter_parameters if also configured in AppSignal

c_src/appsignal_extension.c, config/config.exs, lib/appsignal/nif.ex, lib/appsignal/transaction.ex, test/appsignal/release_upgrade_test.exs, test/appsignal/transaction_test.exs
Available as `to_map` on the `Appsignal.Transaction` module. Allows a
view of the transaction object as is currently stored in the extension.
Used for testing purposes only, do not use this function in your own
apps!
To fetch transaction data from the transaction the extension needs to be
started with a valid config, otherwise it returns an empty string. Since
we want to do this more often, start the AppSignal app with a valid
config by default. Use the `with_config` helper function if you want to
test an invalid config.
Implement one test, setting an action name on the transaction, to make
sure it works from end to end.
Related issue #127
=> Add appsignal_to_json implementation

lib/appsignal/transaction.ex, lib/appsignal/transaction/registry.ex, test/appsignal/transaction/registry_test.exs, test/appsignal/transaction_test.exs
Closes #354 by making sure the Registry GenServer is alive before sending messages to it. When the registry is unavailable, a debug message is logged in [`TransactionRegistry.register/1`](https://github.com/appsignal/appsignal-elixir/blob/65385340bd4692fe3a1ae258f2b7b97853bae0fb/lib/appsignal/transaction/registry.ex#L43).
@lukaszsamson could you try this branch locally and let us know if this resolves the issues you've been running into?
=> Allow calling `Transaction.register/1` and `Transaction.complete/1` when the Registry is not alive

c_src/appsignal_extension.c, lib/appsignal/nif.ex, lib/appsignal/transaction.ex, test/appsignal/transaction_test.exs
Closes #348. Allows overwriting the namespace for an existing Transaction.
=> Add Appsignal.Transaction.set_namespace/1-2

mix_helpers.exs
Continuation of #374. We'll use `gmake` when it's available, so we're sure we're targeting GNU make on systems that have both GNU make and BSD make installed.
=> Use gmake over make when gmake executable exists

agent.exs, c_src/appsignal_extension.c, lib/appsignal.ex, test/appsignal/appsignal_test.exs
The extension now uses doubles for all values, update the type mapping.
Fixes #377 
Part of https://github.com/appsignal/appsignal-agent/issues/353
=> Support doubles in extension

lib/appsignal/config.ex, test/appsignal/config_test.exs
Add support for working_directory_path option.
Docs: https://github.com/appsignal/appsignal-docs/pull/182
~Currently based on PR #384  to include the extension linking fix.~
=> Add working_directory_path config option

lib/appsignal.ex, test/appsignal/appsignal_test.exs
Fixes #396.
Although we don't recommend calling `Appsignal.send_error/1-7` without a stacktrace, and we raise an exception when you do, https://github.com/appsignal/appsignal-elixir/commit/52eee8d84d0f4f23319ea046e53843638bc6e16d introduced a bug which made `send_error/1-7` break when calling it without a stack trace, resulting in the issue described in #396.
=> Allow Appsignal.send_error/1-7 to be called without a stack trace

lib/appsignal/config.ex, test/appsignal/config_test.exs
It's not used for the config in the extension, so remove it to avoid
confusion.
=> Remove unused extension send_params option

test/phoenix/channel_test.exs
Fixes test failures on Decorator 1.2.4 on develop.
Co-authored-by: Jeff Kreeftmeijer <jeffkreeftmeijer@gmail.com>
PR only for build.
=> Create separate modules for testing Appsignal.Phoenix.Channel

Makefile
This fixes the missing `libgcc_s.so` error on AppSignal boot on musl
builds with a two stage deploy.
```
Error loading shared library libgcc_s.so.1: No such file or directory
(needed by /app/lib/appsignal-1.8.1-beta.2/priv/appsignal_extension.so)
```
This was caused by the 1.8 build having more dynamically linked
dependencies than the previous build. This was `libgcc_s`. Since it's
only available as a shared object file (`.so`) we can't specify
`-static` as an option to gcc. Instead, we need to add the
`-static-libgcc` option. Docs:
http://gcc.gnu.org/onlinedocs/gcc/Link-Options.html (search for
`-static-libgcc`).
Fixes:
https://docs.appsignal.com/support/known-issues/compilation-dependencies-required-at-runtime.html
For more information (private issue): …
=> Link gcc to extension .so library

lib/mix/tasks/appsignal.diagnose.ex, test/mix/tasks/appsignal_diagnose_test.exs
By default the list values are printed right after one another, which
makes for unreadable output.
```
request_headers: acceptaccept-charsetaccept-encoding
```
This change joins the list and makes it a comma separated printed list
in the diagnose output.
```
request_headers: accept, accept-charset, accept-encoding
```
Fixes https://github.com/appsignal/appsignal-elixir/issues/379
=> Pretty print lists in diagnose output

mix_helpers.exs
From [support](https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/540654/conversations/18349713842) (private Intercom link).  One of our customers had trouble getting AppSignal to compile while using Distillery’s REPLACE_OS_VARS feature.
When the log_level is set to `:"${LOG_LEVEL}"`, it’s replaced by Distillery. Because that hasn’t happened at compile-time, compiling crashes on `Logger.level_to_number/1`, which doesn’t have a clause for `:"${LOG_LEVEL}"`:
```
==> appsignal
** (FunctionClauseError) no function clause matching in Logger.level_to_number/1 
The following arguments were given to Logger.level_to_number/1:
:"${LOG_LEVEL}"
(logger) lib/logger.ex:465: Logger.level_to_number/1
(logger) lib/logger.ex:463: Logger.compare_levels/2
(logger) lib/logger.ex:578: Logger.bare_log/3 …
```
=> Use `Mix.shell.info` instead of `Logger.info` in mix helpers

agent.exs, lib/appsignal/diagnose/agent.ex, lib/appsignal/system.ex, test/mix/tasks/appsignal_diagnose_test.exs
Support display of new agent & extension diagnose report keys and
values. Drop the requirement of boolean values. If no value display
method is found, show the raw value.
Closes #411
=> Add new agent & extension diagnose report keys 

lib/appsignal/ecto.ex
Adds Telemetry support for Ecto 3.0. Instead of adding `Ecto.Appsignal`
to the :loggers configuration, which is deprecated in 3.x, attach to
Telemetry events instead:
Telemetry.attach("appsignal-ecto", [:appsignal_phoenix_example, :repo, :query], Appsignal.Ecto, :handle_event, nil)
Closes #415.
=> Add Appsignal.Ecto.handle_event/4

mix.exs
Poison 4.0.0 uses some new Elixir 1.6 features which won't work on any
Elixir version lower than 1.6. Use a more restrictive version lock for
Elixir < 1.6 to the dependencies list.
=> Use poison < 4.0 on Elixir < 1.6

lib/appsignal/diagnose/host.ex, lib/mix/tasks/appsignal.diagnose.ex, test/mix/tasks/appsignal_diagnose_test.exs
This field was missing from the report. Add it to the Elixir diagnose
report as well.
=> Add missing host OS field to diagnose report

lib/mix/tasks/appsignal.diagnose.ex, test/mix/tasks/appsignal_diagnose_test.exs
When a user sends a report our way we link back to the AppSignal
diagnose report view page. Initially users will be able to "claim" their
report, so we know who to contact.
Step 2 is making our report validator public so users can see any
validation failures and start debugging themselves, but already keep the
message as such for now so we don't have to ship a new release with an
updated message.
Diagnose CLI updated to match the Ruby gem's output.
https://github.com/appsignal/appsignal-ruby/pull/445
Part of https://github.com/appsignal/appsignal-server/issues/3601
=> Link back to AppSignal diagnose report page

lib/appsignal.ex, lib/appsignal/error_handler.ex, test/appsignal/appsignal_test.exs, test/appsignal/error_handler/error_matcher_test.exs, test/appsignal/error_handler_test.exs, test/support/fake_transaction.ex
As a prerequisite of https://github.com/appsignal/appsignal-elixir/pull/425, this patch switches to using `FakeTransaction` to test if errors are correctly added to the transaction by the `ErrorHandler` instead of relying on its internal state. This is based on https://github.com/appsignal/appsignal-elixir/pull/423, and should be merged after.
=> Use FakeTransaction in ErrorHandler tests

lib/appsignal/diagnose/config.ex, lib/mix/tasks/appsignal.diagnose.ex, test/mix/tasks/appsignal_diagnose_test.exs
Based on #421 
This change print config option sources in diagnose report.
This allows users to track back on their own, based on the output, where
the config options are coming from.
Helps with debugging where a particular option gets set.
It also adds the config options sources to the config report as
described in the format in the PR for the Ruby gem:
appsignal/appsignal-ruby#444
New format:
```
Configuration
diagnose_endpoint: https://appsignal.com/diag
name: appsignal-plug-example (Loaded from file)
active: true
Sources:
default: false
file: true
```
=> Add config option sources to diagnose report

lib/mix/tasks/appsignal.diagnose.ex, test/mix/tasks/appsignal_diagnose_test.exs
Based on #422 
Rebase on develop and change the PRs base branch before merging, after #422 is merged.
If a value was nil or an empty list it wouldn't print anything, as if
was broken.
Now print the config option values to the following rules:
- String: surround with quotes, e.g.: `"foo"`
- Boolean: print raw value, e.g.: `true`
- Atom: print raw value, e.g.: `:foo`
- Lists: print inspect value, e.g.: `["foo", "bar"]`
- Empty lists: print empty list representation, e.g.: `[]`
- Nil values: print nil representation, e.g. `nil`
=> Format values printed in the diagnose

lib/appsignal/config.ex, lib/appsignal/diagnose/paths.ex, lib/appsignal/utils/file_system.ex, lib/mix/tasks/appsignal.diagnose.ex, test/appsignal/config_test.exs, test/appsignal/diagnose/paths_test.exs, test/appsignal/utils/file_system_test.exs, test/mix/tasks/appsignal_diagnose_test.exs, test/support/utils.ex
Set the appsignal.log by default based on the same logic as is present
in Ruby:
https://github.com/appsignal/appsignal-ruby/blob/57b3b7f8a024226c89fb9788a8772047c681ab8f/lib/appsignal/config.rb#L126-L143
With the exception of the preference of the `./log` directory in the
app's directory.
This is not common in Elixir, so instead default to the
`/tmp/appsignal.log` path.
Fixes #391
=> Fix appsignal.log default path

agent.exs
- Support container memory host metrics
- Change `files_world_accessible` permissions to not make files
executable
- Make debug logging for disk IO metrics more robust
Includes changes made in #395
=> Bump agent to 86b6269

lib/appsignal/diagnose/config.ex
```
==> appsignal
Compiling 37 files (.ex)
warning: unused alias Config
lib/appsignal/diagnose/config.ex:2
```
=> Remove unused alias, resolves warning.

lib/appsignal/ecto.ex
For telemetry >= 0.3.0, there is a new calling convention as it is now implemented in Erlang not Elixir. This updates the docs to reflect this.
=> Document how to attach to new telemetry versions.

lib/appsignal/diagnose/paths.ex, test/appsignal/config_test.exs, test/appsignal/error_handler/error_matcher_test.exs
Aside from the fixes in #437, there were some tests failing on 1.8.0:
1. `System.cwd/0` is deprecated and throws a warning.
2. Had to increase the sleeps in ErrorMatcherTest to get them to work. Removing sleeps in favor of retries in the test suite is on my list.
3. Made a stacktrace regex more flexible, because code got moved around in 1.8
=> Get tests to pass on Elixir 1.8

lib/mix/tasks/appsignal.install.ex, test/appsignal/diagnose/report_test.exs, test/mix/tasks/appsignal_install_test.exs
Elixir’s default environments are called “dev”, “test” and “prod”, as
opposed to Rails’ “development”, “test” and “production”.
This patch changes the recommended APPSIGNAL_APP_ENV from “production”
to “prod” in the installer, when selecting environment variable
configuration.
=> Recommend "prod" instead of "production" in installer

.gitignore, lib/appsignal/diagnose/library.ex, lib/appsignal/system.ex, lib/mix/tasks/appsignal.diagnose.ex, mix.exs, mix_helpers.exs, test/appsignal/system_test.exs, test/mix/tasks/appsignal_diagnose_test.exs
Ruby counterpart: https://github.com/appsignal/appsignal-ruby/pull/450
Server PR: https://github.com/appsignal/appsignal-server/pull/3917
---
This report allows us to see what the environment was when the AppSignal
extension was installed, so we can compare it to the diagnose report
generated by `mix appsignal.diagnose` afterwards.
Basic information, such as information about Elixir, the chosen agent
and extension build.
Combine the information from the `install.log` and
`appsignal.architecture` files in one file that stores more easily
parseable metadata.
Extension installation subreport section
=> Store extension installation details in report

lib/appsignal/transaction/registry.ex, test/appsignal/transaction/registry_test.exs
Closes #440.
Ignoring PIDs in a cast in the TransactionRegistry caused race conditions in some situations, which caused errors reported in Plug apps to be registered again in the error logger. This caused `ErlangError`s wrapped in tuples to appear in AppSignal, in the "web" namespace.
This patch makes sure to block when updating the ets table.
*NOTE*: This is a hotfix to be released as 1.9.1.
=> Block on ignoring pids in TransactionRegistry

lib/appsignal/plug.ex, test/appsignal/plug_test.exs
Like https://github.com/appsignal/appsignal-ruby/issues/183, but for Elixir. As requested via [support](https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/540654/conversations/20586098866) (private Intercom link). Opening this pull request instead of an issue since the implementation was mostly done answering their question.
I recommend tagging samples manually until we merge this. That would look something like this;
```elixir
defmodule AppsignalPhoenixExampleWeb.PageController do
use AppsignalPhoenixExampleWeb, :controller
def index(conn, _params) do
conn = render(conn, "index.html")
Appsignal.Transaction.set_sample_data("tags", %{status: to_string(conn.status)})
conn
end
end
```
When using the temporary solution: Some things to note is to update the conn with the result of your …
=> Add response status codes to Plug samples

.travis.yml, lib/mix/tasks/appsignal.diagnose.ex, test/mix/tasks/appsignal_diagnose_test.exs
This environment broke (more noticeably) after PR #433 added more files to
the `priv/` directory that weren't cleaned properly before running the
test suite. The other test environments left artifacts in the `priv/`
dir that were reused by the `test_no_nif` test suite while they
shouldn't have been.
Clean up the `priv/` dir properly and fix the tests to test it properly.
=> Fix tests for test_no_nif test environment

Makefile, lib/appsignal/diagnose/paths.ex, lib/appsignal/nif.ex, mix_helpers.exs, test/mix/tasks/appsignal_diagnose_test.exs
When a warning occurs during the extension installation, fail the
installation. Currently warnings such as linking issues are not cause
for a failed installation, such as #406.
This was replicated by trying to install the linux-gnu build on macOS,
this did not caused the installation to be registered as "failed". This
was unexpected behavior.
Since we don't think the `install.log` will catch any more problems than
the `install.report` now that it also fails on warnings, remove the
`install.log` and instead print the error in the app's STDOUT so the
user can see if anything is wrong.
=> Fail AppSignal extension installation on warnings

lib/appsignal.ex, lib/appsignal/error_handler.ex, lib/appsignal/error_logger_handler.ex, lib/appsignal/logger_handler.ex, test/appsignal/error_handler_test.exs, test/appsignal/error_logger_handler_test.exs, test/appsignal/logger_handler_test.exs
Closes https://github.com/appsignal/appsignal-elixir/issues/442.
Instead of switching to Elixir's `Logger`, which doesn't seem to have a way to extract the error object and stack trace, this pull request uses Erlang's `:logger`, which was introduced in OTP 21, for OTP 21 and up. It falls back to using `:error_logger` for earlier OTP versions.
To do this, the report handling logic was moved from `ErrorHandler` to one module for `:error_logger` and one for `:logger`. The application module [decides](https://github.com/appsignal/appsignal-elixir/blob/c5eed929cec7016d26a43c6f0c9e703e856fd445/lib/appsignal.ex#L26-L30) which to use, based on the OTP version.
=> Use :logger instead of :error_logger on OTP >= 21

lib/appsignal/plug.ex, test/appsignal/plug_test.exs
Closes #463. The `defoverridable` call was dropped in a7b434c7c107a40738f4e42395e8c3a34e798739 when splitting the Plug integration from the Phoenix integration.
=> Allow Appsignal.Plug.call/2 to be overridden

lib/appsignal.ex, lib/appsignal/probes/probes.ex, test/appsignal/probes/probes_test.exs, test/support/fake_probe.ex
This adds the first setup for the probing system in the Elixir side.
We use a Genserver that holds all the probes, this Genserver will schedule itself every minute, and then create a Task for every Probe.
The Probes Genserver is supervised by appsignal.ex.
@jeffkreeftmeijer I'm not 100% sure if this tests are enough coverage.
Next steps would be:
1. Create a way to allow probes to be their own Genservers (Some form of Init system)
2. Create the Erlang Probe
=> Minutly Probing for Custom Metrics

config/config.exs, lib/appsignal.ex, lib/appsignal/probes/erlang_probe.ex, test/appsignal/probes/erlang_probe_test.exs, test/support/appsignal/fake_appsignal.ex, test/support/fake_probe.ex, test/support/test_agent.ex
Currently we support the following set of data:
* IO, tagged as Input, and Output
* Scheduler Metrics, tagged as Total, and Online
* Process metrics, tagged as Limit, and Count
* Memory, tagged as: total, processes, processes_used, system, atom,
atom_used, binary, code, ets
In the future we might want to expand this with Scheduler utilization
and maybe more memory allocations.
=> Add Erlang Probe

lib/appsignal/instrumentation/decorators.ex, test/appsignal/instrumentation/decorator_test.exs
f319d28d9f4b3f6cd427aae973c7b6caa1d4886b introduced a regression where
functions decorated with the `transaction` decorator were run before
their transaction was started. This caused any nested events to be
dropped and results in empty transactions being reported.
This was caused by unquoting the body in the `transaction/3` without
wrapping it in an anonymous function, causing the function to run
immediately and its return value being added as the body parameter in
the `in_transaction/3` function.
This patch adds a regression test to make a function with the
`transaction` decorator that calls a function with the
`transaction_event` decorator produces a transaction with an event, and
wraps the function body in an anonymous function that's called in the
`in_transaction/3` function after …
=> Make sure events are added to transactions started with decorators

lib/appsignal/config.ex, lib/appsignal/probes/probes.ex, test/appsignal/config_test.exs, test/appsignal/probes/probes_test.exs
Allow users to completely disable the minutely probes feature in case of
an issue or if they don't want the metrics to be collected by default.
=> Add enable_minutely_probes config option

config/config.exs, lib/appsignal/probes/erlang_probe.ex, test/appsignal/probes/erlang_probe_test.exs, test/support/fake_inet.ex
Make sure we set the Hostname and HostMetric tag for all the gauges in the Erlang Probe.
=> Set extra tags erlang

lib/appsignal/probes/erlang_probe.ex, test/appsignal/probes/erlang_probe_test.exs
Fall back to using the :inet hostname when no :appsignal config is
defined. Only use the one from the config when the config exists and has
a :hostname key.
=> Don't use fetch_env!/2 in ErlangProbe

test/appsignal/error_handler/error_matcher_test.exs, test/appsignal/error_handler_test.exs, test/appsignal/error_logger_handler_test.exs, test/appsignal/instrumentation/helpers_test.exs, test/appsignal/logger_handler_test.exs, test/appsignal/plug_test.exs, test/appsignal/probes/probes_test.exs, test/support/utils.ex
To remove the sleeps that caused timing issues CI, this patch adds the `until/1` and `repeatedly/1` test helpers to deal with timing-sensitive tests. The former retries an assertion every 10 ms until no AssertionError is raised, and the latter runs a function for ten times to make sure no failure happens in a 100 ms timespan.
=> Remove sleeps from tests

lib/appsignal/utils/map_filter.ex, test/appsignal/transaction/filter_test.exs
As reported in https://app.intercom.io/a/apps/yzor8gyw/users/5c0137be92ce92ecda020682/all-conversations. Although Phoenix exclusively uses string keys, Addict uses atom keys. This patch adds support for atom keys besides string keys.
=> Handle atom keys in MapFilter.filter_values/2

lib/appsignal/error_handler.ex, lib/appsignal/transaction.ex, lib/appsignal/transaction/registry.ex, test/appsignal/plug_test.exs, test/appsignal/transaction/registry_test.exs, test/support/appsignal/fake_transaction.ex
Part of #476. 
This patch removes and deprecates `TransactionRegistry.ignored?/0`, which is now handled using `lookup/0` directly instead, to reduce the amount of work being done in the Registry process.
=>  Implicitly check ignored transactions in `TransactionRegistry.lookup/1`

lib/appsignal/ecto.ex, test/appsignal/ecto_test.exs
After adding a regression test for the work in #478, the build [failed](https://travis-ci.org/appsignal/appsignal-elixir/builds/522068288) on 1.3.x because `:nanoseconds` wasn't accepted in `System.convert_time_unit` in older versions.
This patch cherry-picks that regression test, uses `1_000_000_000` (which is accepted as nanoseconds in all versions), and makes sure to convert for all callbacks in the Ecto integration. The native time is usually in nanoseconds, but this makes sure we're always reporting correctly. 
Fixes #385, although we should disable completely, which is in #478 (and is now based on this branch).
=>  Convert time units for all Ecto callbacks

lib/appsignal/demo.ex, lib/appsignal/ecto.ex, lib/appsignal/phoenix/instrumenter.ex, lib/appsignal/plug.ex, lib/appsignal/transaction.ex, lib/appsignal/transaction/registry.ex, lib/mix/tasks/appsignal.demo.ex, test/appsignal/ecto_test.exs, test/appsignal/plug_test.exs, test/appsignal/transaction/registry_test.exs, test/appsignal/transaction_test.exs, test/phoenix/instrumenter_test.exs
Closes #409.
This patch makes sure not to start transactions when AppSignal is configured to not be active. The `Transaction` and `Registry` modules won't create, register or lookup Transactions, and the `Plug` will only call `super` in the host application's `call/2` function.
The demo command doesn't work when AppSignal is disabled, so it prints an error to explain to run the diagnose command instead, like we do in the Ruby intergation (but with a link to the documentation, which I'll also propose for Ruby).
=> Deactivate AppSignal when not active

mix_helpers.exs, test/mix/helpers_test.exs, test/support/fake_system.ex
Closes #477. Aside from tuples, `System.cmd/2` can raise POSIX errors.
This patch makes sure that doesn't break compilation.
Based in master to publish this as a patch release.
=> Handle errors in Mix.Appsignal.Helper.uid/0

.travis.yml
Only build the master and develop branches automatically. Prevents
double CI builds from triggering for every PR.
=> Do not build every branch automatically

Makefile, scripts/test
Update it to clean all files that are in the `priv/` dir of the package.
Also set a default value to the `LIB_DIR` if it's not set. This is
usually set by the `mix_helpers.exs` file instead, but in case we run
`make clean` directoy, it is not set.
=> Update make clean task

.travis.yml, lib/appsignal/instrumentation/helpers.ex, lib/appsignal/transaction.ex, scripts/run_formatter, test/appsignal/instrumentation/helpers_test.exs, test/appsignal/transaction_test.exs
Since #480, `TransactionRegistry.lookup/1` can return `:ignored`. This patch makes sure every function that handles Transactions have a wildcard to ignore those instead of explicitly matching on nil.
=> Handle :ignored Transactions in Transaction and Instrumentation.Helpers

Makefile
The linker on FreeBSD 12 and up does not support `-fatal_warnings`
option anymore. Instead use `--fatal-warnings` which does the same
thing.
As reported in #483
Based on #484
=> Fix FreeBSD fatal warnings linking flag

mix_helpers.exs, test/mix/helpers_test.exs
Inspired by #483. 
This patch makes sure errors (non-zero status codes) from the ldd command are properly handled, as well as situations where the command doesn't include a parsable version number.
=> ldd version error handling

lib/appsignal/transaction/registry.ex
The integration will log on startup, so these are not needed and too
verbose now the integration can be disabled completely.
=> Remove log statements from TransactionRegisty

lib/appsignal/transmitter.ex, test/appsignal/transmitter_test.exs
OTP 22 requires the ciphers to be explicitly set for hackney's HTTPs requests to succeed.
=> Explicitly set ciphers in hackney https requests

Makefile
On my local test setup I needed more LDFLAGS (linking flags) for the
FreeBSD build to work.
Without it the following error would be returned on Nif.start:
```
warning: Error loading NIF (Is your operating system
(amd64-portbld-freebsd11.2) supported? Please check
http://docs.appsignal.com/support/operating-systems.html):
Failed to load NIF library:
'/path/_build/dev/lib/appsignal/priv/appsignal_extension.so:
Undefined symbol "appsignal_running_in_container"'
(appsignal) lib/appsignal/nif.ex:48: Appsignal.Nif.init/0
(kernel) code_server.erl:1347: anonymous fn/1 in
:code_server.handle_on_load/5
```
=> Fix FreeBSD compilation

mix_helpers.exs
Like #489, but for downloading the agent. The code is duplicated from
Appsignal.Transmitter, as that module is not yet compiled at compile
time.
=> Use the bundled certificate and ciphers when downloading agent

mix_helpers.exs
The command `ldd --version` always returns exit code `1`.
This is because `--version` is not a supported option, it always prints
the version number when it runs into an issue when starting.
It's mostly there so we know what it's doing.
Because it always returns exit code `1`, don't listen to the exit code.
Only check if the command does not exist. That raises an error which we
catch instead and only then return an error tuple.
This behavior broke in #487
Fixes https://github.com/appsignal/support/issues/19
=> Fix musl detection on installation

mix.exs
Support for Elixir 1.3 was
[dropped](https://github.com/phoenixframework/phoenix/blob/v1.4/.travis.yml)
in Phoenix 1.4. As Phoenix 1.4.8 now expects :telemetry_handler_table
to be running, we've reached incompatibility between Elixir 1.3 and
Phoenix 1.4, so we're dropping support for this specific combination as
well.
=> Use Phoenix >= 1.2.0 and < 1.4.0 on Elixir 1.3

lib/appsignal/config.ex, test/appsignal/config_test.exs
Ecto 2.x's logger, which we use to instrument queries on Ecto < 3, logs events when running migrations. Since https://github.com/appsignal/appsignal-elixir/pull/480/files on 1.10.5, we explicitly check if the configuration is active when creating a Transaction. For unconfigured applications, or applications that start without loading the AppSignal dependency (like migrations), the check fails, as the configuration isn't yet converted to a map.
To fix this, this patch adds an explicit pattern to match on (`%{valid: true, active: true}`) in `Config.active?/2`. Anything that doesn't match this pattern returns `false`, which disables the integration.
=> Disable integration for non-map configurations

lib/appsignal/phoenix/channel.ex, lib/appsignal/plug.ex, lib/appsignal/transaction.ex, lib/appsignal/utils/map_filter.ex, test/appsignal/transaction/filter_test.exs
It includes support for the special syntax `{:keep, params}` for parameter filtering from [Phoenix](https://hexdocs.pm/phoenix/Phoenix.Logger.html#module-parameter-filtering).
It also fixes a bug when merging the filtering configurations of Appsignal and Phoenix as reported in
https://github.com/appsignal/appsignal-elixir/issues/498
Most of the implementation is a copy of the [`Phoenix.Logger`](https://github.com/phoenixframework/phoenix/blob/4d61eacd83d61899a895167715d8754c5c8187be/lib/phoenix/logger.ex#L61)
It closes #498
=> Support parameter filtering with {:keep, params}

lib/appsignal/utils/map_filter.ex, test/appsignal/transaction/filter_test.exs
As reported in https://github.com/appsignal/appsignal-elixir/pull/499#issuecomment-512785992, #499 breaks backwards compatibility by removing the `get_filter_parameters/0` and `get_filter_session_data/0` functions. 
This patch restores these two functions. These aren't deprecated, as they're now used by the current implementation, so they're still part of the API.
=> Restore get_filter_(parameters|session_data) to patch backwards compatibility

lib/appsignal.ex, lib/appsignal/transaction/ets.ex, lib/appsignal/transaction/receiver.ex, lib/appsignal/transaction/registry.ex, test/appsignal/transaction/registry_test.exs, test/appsignal/transaction_test.exs
This pull request contains @BenMorganIO's changes, submitted in https://github.com/appsignal/appsignal-elixir/pull/504. I'm opening this one here as the original included some unrelated fixes to the test suite and a benchmark for the Registry, which are already merged.
I've also removed the style changes from the original pull request's commits, to make this easier to review and push out as a new release. We should decide on a coding and documentation style, but we're definitely willing to clean the codebase up in this regard.
Ben's functionality remains unchanged and has been working great in my testing. @tombruijn and @jvanbaarsen could you try this branch in your apps, to make sure everything still works as you'd expect? I haven't seen it fail, but one place this patch might have an …
=> Extract ETS and Receiver logic from TransactionRegistry

lib/appsignal/diagnose/agent.ex, lib/appsignal/diagnose/report.ex, lib/appsignal/json.ex, lib/appsignal/transaction.ex, lib/mix/tasks/appsignal.diagnose.ex, mix.exs, mix_helpers.exs
Closes #474.
Instead of depending directly on Poison, this patch adds support for the now-preferred Jason.
Both the Jason and Poison dependencies are made optional, so projects that don't depend on a JSON encoder (which should be a very small number) are asked to depend on Jason in explicitly when trying to build the installation- or diagnose reports.
=> Add support for both Jason and Poison

lib/appsignal/transmitter.ex, mix_helpers.exs, test/appsignal/transmitter_test.exs
In Erlang OTP 22.1 the honor_cipher_order option gives an error. hackney
sets this by default to `true`. Setting it to `:undefined` (and not
`false`) unsets the option so requests made with hackney work again.
Workaround for #512 
Based on #514
=> hackney workaround for honor_cipher_order

mix_helpers.exs
Poison won't work if you try to convert tuples to JSON. Error return
values from the download an install steps can return tuples.
Make sure that all the error values are a string before they are
converted to JSON. This way the report generation won't fail and crash
the installation. Then it can get send along with the diagnose report as
normal.
```elixir
%{
result: %{
message: "{:error, {:error, {:option, :server_only, :honor_cipher_order}}}",
status: :failed
}
}
```
=> Ensure all report values are strings

lib/appsignal/utils/map_filter.ex, test/appsignal/transaction/filter_test.exs
The `MapFilter` is used to filter parameters and session data before sending it to AppSignal. Currently, it filters nested maps and lists. Structs aren't generally found in parameter maps, unless a plug adds them when parsing the parameters. We've seen this in the [open_api_spex](https://github.com/open-api-spex/open_api_spex) library, where it's not an issue as the extracted parameter struct isn't actually added to the params map.
However, since it makes sense to properly filter structs if they end up in the parameters, this patch adds struct filtering by converting both maps and stucts to lists, and then filtering those. 
It also includes a general cleanup in the tests for `MapFilter`, which is contained in c7de233 and includes no structural changes.
=> Filter structs in MapFilter

lib/appsignal/probes/erlang_probe.ex, test/appsignal/probes/erlang_probe_test.exs
This adds a new metric to the Erlang Probe to gather the
`run_queue_length`.
@jeffkreeftmeijer I also assigned you to this PR, since I need your help to get a better sense on how we can best expose this metric.
=> Add Erlang Run Queue length metric

lib/appsignal/instrumentation/decorators.ex, lib/appsignal/phoenix/channel.ex, test/appsignal/instrumentation/decorator_test.exs, test/phoenix/channel_test.exs, test/support/appsignal/fake_transaction.ex
Since 1.11.0, `Appsignal.Transaction.complete/1` can return `nil` if
there was no Transaction to be completed. When AppSignal is disabled and
while using transaction decorators, this could result in a broken
match. This patch removes the match.
=> Don't match on return from `Transaction.complete/1`

lib/appsignal/plug.ex, lib/appsignal/transaction.ex, test/appsignal/transaction_test.exs
Instead of checking wether action names are `nil` in the `Plug` module, this patch moves the check to `Transaction.set_action/2`. This allows the function to be called without having to check it first, like we've seen happening with LiveView requests.
=> Move action nil-check to Appsignal.Transaction.set_action/2

lib/appsignal/transaction/receiver.ex, test/appsignal/transaction/receiver_test.exs
As reported in https://github.com/appsignal/appsignal-elixir/issues/524,
a regression in version 1.11.0 caused an issue where rows aren't
properly deleted from the ETS table. This causes slowdowns in
`Appsignal.TransactionRegistry.pids_and_monitor_references/1`.
=> Run receiver monitors in receiver process

agent.exs, lib/appsignal/config.ex, test/appsignal/config_test.exs
This patch adds the `transaction_debug` and `APPSIGNAL_TRANSACTION_DEBUG_MODE` configuration option, and bumps the agent to f6353b4, which includes the new debug mode.
This will be released as version 1.11.4.
=> Add transaction_debug configuration option

lib/appsignal/error_handler.ex, lib/appsignal/phoenix/channel.ex, test/phoenix/channel_test.exs
In current versions of the integration, exceptions raised in channel actions fall through and get picked up by the error handler, which adds the exception to the Transaction that's opened by the channel instrumentation.
This, however, skips setting the environment data, which happens at the end of the Transaction for performance samples. The code never reaches that, as the exception isn't caught.
This patch adds a `try`-block to the channel instrumentation to make sure the error is caught there, and allowing the environment data to be set in the `catch` block.
=> Add explicit error handling for Phoenix channels

lib/appsignal/error.ex, lib/appsignal/instrumentation/decorators.ex, lib/appsignal/plug.ex, lib/appsignal/utils.ex, test/appsignal/instrumentation/decorator_test.exs, test/appsignal/utils_test.exs
We currently have two functions that clean up module names, in both `AppSignal.Plug` and `AppSignal.Error`. As reported in #529, module names from the decorators weren't cleaned up.
This patch moves to a single implementation in `Appsignal.Utils`, and uses it from `Plug`, `Error`, and `Decorators`.
Closes #529.
=> Move module name cleanup to Appsignal.Utils, clean up module names from decorators

lib/appsignal.ex, lib/appsignal/phoenix/event_handler.ex, lib/appsignal/phoenix/instrumenter.ex, lib/appsignal/plug.ex, mix.exs, test/appsignal/plug_test.exs, test/phoenix/event_handler_test.exs, test/phoenix/instrumenter_test.exs, test/support/appsignal/fake_transaction.ex
Phoenix 1.5 [removes the instrumentation API](https://github.com/phoenixframework/phoenix/commit/19b0b01e2fc751901e06fcd74db1fc5b39672d26) in favour of using Telemetry. This pull request adds a Telemetry event handler that catches `[:phoenix, :endpoint, :start]` and `[:phoenix, :endpoint, :stop]` events to create an event named `call.endpoint`, which is comparable to `call.controller` in the current version.
> Before version Phoenix version 1.5. AppSignal’s Phoenix instrumentation depended on data from the Phoenix instrumenter, and the installation instructions included a step to attach AppSignal’s instrumenter to your application in your app’s configuration:
> 
> ```
> config :appsignal_phoenix_example, AppsignalPhoenixExampleWeb.Endpoint,
>   #...
>   instrumenters: …
```
=> Add Phoenix Telemetry event handler to add Phoenix 1.5 instrumentation

.travis.yml, lib/appsignal/transaction/receiver.ex, lib/appsignal/transmitter.ex, mix_helpers.exs, scripts/test, test/appsignal/transaction/receiver_test.exs, test/appsignal/transmitter_test.exs, test/phoenix/transaction/filter_test.exs, test/support/appsignal/fake_transaction.ex
Hackney drops all default ssl options when passing any custom options.
This patch adds the required defaults to the custom options passed in in
Appsignal.Transmitter.
To test this, use the Transmitter to request a resource from a self-signed domain:
```
Appsignal.Transmitter.request(:get, "https://self-signed.badssl.com/") 
```
=> Use a complete set of ssl_options for Hackney

.travis.yml, lib/appsignal/diagnose/agent.ex, scripts/test, test/appsignal/backtrace_test.exs, test/appsignal/error_handler/error_matcher_test.exs
This patch adds Elixir 1.10 to the build matrix on CI, and makes sure to run the formatter on 1.10 (as it's the latest version). It also fixes some assertions caused by updates in Elixir's backtrace lines:
> Elixir 1.10 adds version numbers in the app names in backtrace lines.
> This patch adds an optional version number to all places where a
> backtrace line is asserted on.
=> Run Elixir 1.10.0-rc.0 on CI, update tests for 1.10

lib/appsignal/phoenix/event_handler.ex, lib/appsignal/plug.ex, test/appsignal/plug_test.exs, test/phoenix/event_handler_test.exs, test/phoenix/instrumenter_test.exs
After #528, which adds Telemetry-based instrumentation to add support for Phoenix 1.5—which removes the `Phoenix.Instrumenter` module we previously relied on—this patch adds an event handler for `[:phoenix, :router_dispatch, :start]` events, which include the controller and action names in their metadata.
Since this event is called before the action is executed, we can set the action name directly on the Nif, and have it be overwritten in the controller action by calling the same function again later. Also, unwrapped errors (like exits) have their action names properly added if they happen in a controller action.
To test this, use a Phoenix 1.5 application and make sure the action names are set correctly and can be overwitten. Also, make sure errors have the correct action names added. A …
=> Set Phoenix 1.5 action names in the EventHandler

.travis.yml, lib/appsignal/transaction/receiver.ex, lib/appsignal/transaction/registry.ex, test/appsignal/transaction/receiver_test.exs
In #525, which moved the monitors in Transaction.Receiver to their own
processes, the call to demonitor processes was made asyncronous.
Because of this, calling Registry.pids_and_monitor_references/1 from the
Transaction.Receiver could cause a race condition where the entry was
removed from ets before the Receiver could get the monitor references
from the table, preventing monitors from being removed.
For high-throughput apps with multiple Transactions created from the
same process through custom instrumentation, this could cause slow
memory increases because of piling up process monitors.
This patch moves the call to pids_and_monitor_references/1 to the
Registry, making it run synchronously before calling out to the
Receiver, ensuring the record exists when demonitoring processes.
Closes …
=> Call pids_and_monitor_references/1 from TransactionRegistry

bench/transaction_match.exs, lib/appsignal/transaction/registry.ex, test/appsignal/transaction/registry_test.exs
To reduce the time spent looking up Transactions in ETS, this pull request removes backwards compatibility fixes introduced in e8c481f905736ed54402dc5304efd3269cda1574 back in 2018. 
From my testing, this branch speeds the creation and removal of a transaction up to 30K per second, which is a 50% speedup compared to 1.11.7.
=> Reduce calls to pids_and_monitor_references/1 and :ets.match/1

lib/appsignal/phoenix/event_handler.ex, test/phoenix/event_handler_test.exs
As reported in #546, mounted plugs have the ability to pass non-atom
plug_opts. This patch makes sure the Phoenix.EventHandler ignores them
instead of trying to convert the options to an action name.
=> EventHandler handles router_dispatch events with plug_opts

lib/mix/tasks/appsignal.install.ex
First of all, I'd like to thank you guys for providing such a wonderful service. I myself heavily use Appsignal in production.
Recently while I was installing Appsignal for a new project, I came across an error message like this:
```
AppSignal install
================================================================================
...
Validating Push API key: ** (Protocol.UndefinedError) protocol String.Chars not implemented for {:options, {:sslv3, {:versions, [:"tlsv1.2", :"tlsv1.1", :tlsv1, :sslv3]}}} of type Tuple
(elixir 1.10.1) lib/string/chars.ex:3: String.Chars.impl_for!/1
(elixir 1.10.1) lib/string/chars.ex:22: String.Chars.to_string/1
(elixir 1.10.1) lib/io.ex:669: IO.puts/2
lib/mix/tasks/appsignal.install.ex:80: Mix.Tasks.Appsignal.Install.validate_push_api_key/0 …
```
=> Installing messaging got improved

lib/appsignal/phoenix/channel.ex
Fixes #552
I decided to keep `atom` too as people might be using this [without decorators](https://hexdocs.pm/appsignal/Appsignal.Phoenix.Channel.html#module-instrumenting-without-decorators).
=> Fix typespec for Appsignal.Phoenix.Channel.channel_action/4

mix.exs
=> Relax live_view dependency to allow versions over 0.9

.travis.yml, lib/appsignal.ex, lib/appsignal/demo.ex, lib/appsignal/phoenix/channel.ex, lib/appsignal/phoenix/live_view.ex, lib/appsignal/plug.ex, lib/appsignal/stacktrace.ex, test/appsignal/stacktrace_test.ex, test/appsignal/stacktrace_test.exs
`System.stacktrace/0` was deprecated and replaced with `__STACKTRACE__/0` in Elixir 1.7. Current versions throw deprecation warnings, so we're moving to using the new method on versions that have it available.
=> Use `__STACKTRACE__ /0` on Elixir >= 1.7

agent.exs, c_src/appsignal_extension.c, lib/appsignal/config.ex, lib/appsignal/nif.ex, lib/appsignal/span.ex, lib/appsignal/utils/data_encoder.ex, lib/appsignal/utils/map_filter.ex, lib/mix/tasks/appsignal.install.ex, test/appsignal/config_test.exs, test/appsignal/span_test.exs, test/appsignal/utils/map_filter_test.exs
Filters parameters and session data using the agent's data filtering introduced in https://github.com/appsignal/appsignal-agent/pull/530. Filtered keys can be configured using the `:filter_data_keys`/`APPSIGNAL_FILTER_DATA_KEYS` configuration option.
For backwards compatibility, the keys in  `:filter_parameters`/`APPSIGNAL_FILTER_PARAMETERS` and `:filter_session_data`/`APPSIGNAL_FILTER_SESSION_DATA` are automatically added to the filtered data keys.
For more backwards compatibility, this patch supports Phoenix' Logger filter :keep-lists. With configuration like this in a Phoenix app;
```
config :phoenix, :filter_parameters, {:keep, ["name"]}
```
All keys are filtered except for "name" before sending data to the agent.
=> Filtered data

lib/appsignal/transmitter.ex
As part of https://github.com/appsignal/appsignal-elixir/issues/562, we've seen issues on OTP 23 when trying to send the diagnose report when running `mix diagnose --send-report`.
```
Send diagnostics report to AppSignal? (Y/n): y
Transmitting diagnostics report
16:36:35.835 [info]  TLS :client: In state :hello received SERVER ALERT: Fatal - Handshake Failure
Error: Something went wrong while submitting the report to AppSignal.
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:tls_alert, {:handshake_failure, 'TLS client: In state hello received SERVER ALERT: Fatal - Handshake Failure\n '}} of type Tuple
```
This patch switches to tls 1.3 (which is the default on OTP 23) ciphers on OTP 23 to fix this issue.
=> Use tls 1.3 cipher suites on OTP 23

c_src/appsignal_extension.c, lib/appsignal/span.ex, test/appsignal/span_test.exs, test/support/appsignal/test_nif.ex
Implements `Nif.set_span_namespace/2` to call to the extension instead of the Nif's noop.
=> Implement _set_span_namespace

lib/mix/tasks/appsignal.install.ex, test/mix/tasks/appsignal_install_test.exs
This patch makes sure newer Elixir apps, which don't have a `config/config.exs` file anymore, still get a linked `config/appsignal.exs` file by creating `config/config.exs` if it doesn't exist, instead of trying to append to it.
=> Link AppSignal config when config/config.exs does not exist

lib/appsignal/instrumentation/decorators.ex, test/appsignal/instrumentation_test.exs
To reduce duplication when adding categories to the decorator functions, the
call to `Appsignal.Instrumentation.instrument/2` is moved to
`Decorators.do_instrument/2` to allow adding the namespace to the context map.
This way, the `instrument/2-3` function does not need another public head to
handle categories.
When calling the transaction_event decorator while passing a category, this patch 
makes sure the category is set like it was in the previous versions of the integration.
=> Set categories from `transaction_event/3` decorator fallback 

lib/appsignal/instrumentation.ex, lib/appsignal/instrumentation/decorators.ex
Since the `Span.set_attribute/3` function takes and returns `Span`s and `nil`s,
we don't care about the return value here, as either case is accounted for.
Part of closing https://github.com/appsignal/appsignal-elixir-phoenix/issues/5.
=> Explicitly ignore returns from Span functions 

lib/appsignal/error/backend.ex, test/appsignal/error/backend_test.exs
Closes #590.
Based on the work done by @anronin in #591, this patch also includes a fix for the Dialyzer issue caused by the `ok?/1` helper function.
=> Ignore unhandled info, code_change and terminate in Error.Backend

lib/appsignal/transaction_registry.ex
A customer reported that they used this function and that it was a hard fail, add a stub so one would get the deprecation warning instead.
=> Add register stub to deprecated transaction registry

lib/appsignal/ecto.ex, test/appsignal/ecto_test.exs
As reported via [support](https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700017831).
Since 2.0, we're not dropping Spans anymore when they don't have a parent Span.
While that makes technical sense, users are seeing spikes in usage because
previously ignored queries that happened outside of any web requests are now
instrumented.
This patch reverts that behaviour to how it worked in 1.x. If a query happens
when there's no parent to conatain it, the query isn't instrumented.
=> Don't register query spans without parents

agent.exs, c_src/appsignal_extension.c, lib/appsignal/nif.ex, lib/appsignal/span.ex, test/appsignal/nif_test.exs, test/appsignal/span_test.exs, test/appsignal/tracer_test.exs, test/support/appsignal/test_nif.ex
Changes required for https://github.com/appsignal/appsignal-agent/pull/643. This patch fixes the agent CI for that patch: https://appsignal.semaphoreci.com/workflows/a84adb27-c37b-48a9-b288-0c5d02fd2505.
=> Switch to reference-based child Span API

lib/appsignal/monitor.ex, lib/appsignal/tracer.ex, test/appsignal/appsignal_test.exs, test/appsignal/demo_test.exs, test/appsignal/ecto_test.exs, test/appsignal/instrumentation_test.exs, test/appsignal/monitor_test.exs, test/appsignal/tracer_test.exs, test/mix/tasks/appsignal_install_test.exs
To make extra-sure spans are cleaned up if their process exits, even if the
span wasn't closed and should be dropped, this patch adds a monitor when
registering a span in the ets table.
=> Monitor all registered spans

lib/appsignal/instrumentation.ex, test/appsignal/instrumentation_test.exs
Set error used the current span, which caused errors to not be tracked. Always use the root span instead.
=> Let set error use root span

lib/appsignal/error.ex, lib/appsignal/instrumentation.ex, lib/appsignal/span.ex, lib/appsignal/test/span.ex, test/appsignal/error_test.exs, test/appsignal/instrumentation_test.exs, test/appsignal/span_test.exs
This patch adds `send_error/3` and `set_error/2`, which take an Elixir exception struct instead of a kind and reason:
try do
raise "Exception!"
rescue
exception -> Appsignal.set_error(exception, __STACKTRACE__)
end
Part of the improvements we’re making for #610.
=> Pass Elixir exceptions to `Appsignal.Instrumentation.se(t|nd)_error/2`

.semaphore/semaphore.yml, lib/appsignal.ex, lib/appsignal/instrumentation/helpers.ex, lib/appsignal/monitor.ex, lib/appsignal/probes/probes.ex, lib/appsignal/tracer.ex
Fixes compiler warnings and adds a `--warnings-as-errors` check to CI.
Closes #592.
Closes https://github.com/orgs/appsignal/projects/35#card-52652361.
=> Clear warnings

lib/appsignal/instrumentation.ex, test/appsignal/instrumentation_test.exs
`send_error/2-4` takes a function as the last argument to add extra metadata.
```
try do
raise "Exception!"
rescue
exception ->
Appsignal.send_error(exception, __STACKTRACE__, fn(span) ->
Appsignal.Span.set_attribute(span, "key", "value")
end)
end
```
=> Pass fun to set error

lib/appsignal/error/backend.ex, test/appsignal/error/backend_test.exs
Appsignal.Plug [ignores](https://github.com/appsignal/appsignal-elixir-plug/blob/6eda8784eb27365077f3dce6b75983eec6d02b22/lib/appsignal_plug.ex#L61) the current process whenever it catches an exception. That’s done to allow `Appsignal.Error.Backend` to [drop](https://github.com/appsignal/appsignal-elixir/blob/main/lib/appsignal/error/backend.ex#L25-L26) any error reports that came from that process, as those were already handled by `Appsignal.Plug`.
Since plug_cowboy 2.0.2 (https://github.com/elixir-plug/plug_cowboy/commit/6513e38529324283dc7ac430e9f8a3107dbd936d, to be exact), the pid that’s sent to the error logger doesn’t match the pid we’re ignoring. This causes duplicate errors, where one is logged to the “web” namespace (the one caught by `Appsignal.Plug`) and another is logged in …
=> Use pid from conn in Error.Backend if available

lib/appsignal/config.ex, test/appsignal/config_test.exs
As discussed in https://appsignal.slack.com/archives/CNPP953E2/p1614000314014300.
=> Ensure the `:request_headers` config returns an empty list by default

config/config.exs, lib/appsignal.ex, lib/appsignal/config.ex, lib/appsignal/ecto.ex, lib/appsignal/error/backend.ex, lib/appsignal/logger.ex, lib/appsignal/test/logger.ex, test/appsignal/config_test.exs, test/appsignal/logger_test.exs
Adds `Appsignal.Logger.debug/1`, which calls out to `Logger.debug/1`, but only if the `:debug` configuration option is set to `true`.
This is the first part of closing #634, which will require patches to both the Plug and Phoenix packages.
=> Add `Appsignal.Logger` to only log debug messages when the `:debug` configuration is turned on

agent.exs
Changes since 44e4d97:
- Log transaction event name on close in error for debug purposes.
https://github.com/appsignal/appsignal-agent/pull/654
- Warn when adding an error to a child span. This is unsupported.
https://github.com/appsignal/appsignal-agent/pull/656
- Log event digest of span on close in debug log to debug empty events
being reported.
https://github.com/appsignal/appsignal-agent/pull/666
- Fix incidents not being emitted from spans in certain cases.
https://github.com/appsignal/appsignal-agent/pull/673
- Fix empty events being reported for spans occurring in error samples.
https://github.com/appsignal/appsignal-agent/pull/675
[skip review]
=> Bump agent to d08ae6c

lib/appsignal/config.ex
closes https://github.com/appsignal/appsignal-elixir/issues/643
I have this working in the example repo described in #643 in this branch: https://github.com/the-mikedavis/appsignal-compile-time-example-repo/compare/fix-pr-bless and I see a successful compile with no configuration! :tada:
=> use get_env/3 to avoid compilation errors

lib/appsignal/monitor.ex, test/appsignal/monitor_test.exs
As reported through [support](https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700035905#part_id=comment-16410700035905-8913685523) (private Intercom link), we’ve had a customer report message queue buildups in `Appsignal.Monitor` for their high-throughput app caused by our use  of `Process.info(self(), :monitors)`.
This patch moves off calling to `Process.info/2` for every created monitor, and instead keeps an internal list. It’s updated to match the actual list every 60 seconds automatically, although we haven’t found a way to get non-existent pids into the list with the current API.
Closes https://github.com/appsignal/support/issues/128.
=> Keep internal list of monitors in `Appsignal.Monitor` process

lib/appsignal/monitor.ex, test/appsignal/monitor_test.exs
The `Appsignal.Monitor` GenServer was storing a list of pids, but since uniqueness is guaranteed (you can't monitor a particular pid more than once), MapSet is a better data structure to store this information, since all its operations are constant-time instead of linear-time. 
Considering that this GenServer was previously a performance bottleneck in v2.1.6, I think this incremental improvement makes sense to curb potential future performance issues.
=> Replacing AppSignal.Monitor's list state with a MapSet

lib/appsignal/probes/erlang_probe.ex, test/appsignal/probes/erlang_probe_test.exs
As requested in https://github.com/appsignal/support/issues/136, track
the atom limit and current atom count. This way users can set up alerts
based on if they (start to) reach the upper limit.
I've added this as their own `erlang_atom` metric with the `limit` and
`count` type tag values, like how do create metrics for the
`process_limit` and `process_count`.
Closes https://github.com/appsignal/support/issues/136
=> Track erlang atom metrics

.changesets/musl-flag.md, mix_helpers.exs, test/mix/helpers_test.exs
Currently the APPSIGNAL_BUILD_FOR_MUSL flag listens to any value and
accepts that as meaning that the user intends to install the Linux musl
build.
The defined behavior in the integrations guide specifies that the
APPSIGNAL_BUILD_FOR_MUSL env var should listen to the `1` or `true`
values.
Source:
https://github.com/appsignal/integration-guide/blob/9b6fb1491e3aab87cb29b732470c8162f9cd080b/build/installation.md#appsignal_build_for_musl
Update the APPSIGNAL_BUILD_FOR_MUSL flag to listen to only the `1` and
`true` values as agreed upon.
=> Update APPSIGNAL_BUILD_FOR_MUSL flag behavior

.changesets/linux-arm-build.md, agent.exs, mix_helpers.exs, test/mix/helpers_test.exs
Add Linux ARM 64-bit build and put it behind a feature flag.
Users can enable the Linux ARM build with the
`APPSIGNAL_BUILD_FOR_LINUX_ARM` environment variable during
installation. This build is behind a flag by default because it requires
more testing. People may expect it just works because it gets chosen
automatically if we don't put it behind a flag. Now we have an
opportunity to warn them beforehand.
I made the `Mix.Appsignal.Helper.verify_system_architecture` function
public so I could test its behavior like we do for the `agent_platform`
function.
Docs:
https://docs.appsignal.com/support/operating-systems.html#linux-arm-build-override
Integrations docs:
https://github.com/appsignal/integration-guide/blob/main/build/installation.md#appsignal_build_for_linux_arm
=> Add Linux ARM flag to enable experimental build

.changesets/linux-arm-build.md, agent.exs, mix_helpers.exs, test/mix/helpers_test.exs
Redo of PR #654 which was merged on the wrong branch.
[skip review] because it was reviewed in #654.
Add Linux ARM 64-bit build and put it behind a feature flag.
Users can enable the Linux ARM build with the
`APPSIGNAL_BUILD_FOR_LINUX_ARM` environment variable during
installation. This build is behind a flag by default because it requires
more testing. People may expect it just works because it gets chosen
automatically if we don't put it behind a flag. Now we have an
opportunity to warn them beforehand.
I made the `Mix.Appsignal.Helper.verify_system_architecture` function
public so I could test its behavior like we do for the `agent_platform`
function.
Docs:
https://docs.appsignal.com/support/operating-systems.html#linux-arm-build-override
Integrations docs: …
=> Add Linux ARM flag to enable experimental build 

CHANGELOG.md, README.md, mono.yml, script/setup
Use our own tooling for development in the Elixir integration repos.
https://github.com/appsignal/mono/
Follow the instructions on the mono README to install it locally.
Mono is also installed on the CI using the `script/setup` script
which is run before every job. The mono download is cached between
jobs so we don't download it for every job fresh. Update the version
variable `MONO_VERSION` to update the mono install on the CI.
This `setup` script will check the existence of the `cache` command, if
not it will skip it. This allows it to be reused in the test-setups
repo.
Mono repo support for Elixir isn't 100% feature complete yet so we're
first adding it to every repo separately.
I didn't add mono to the Semaphore CI test setup as it doesn't really
add anything there at this point. I …
=> Add mono to project

.changesets/add-linux-arm-override-to-diagnose-report.md, lib/mix/tasks/appsignal.diagnose.ex, mix_helpers.exs, test/mix/tasks/appsignal_diagnose_test.exs
In PR #656 I added the experimental Linux ARM build behind a feature
flag. In the implementation I forgot to add the `linux_arm_override`
value to the diagnose report with which we can detect if this env var
was set during installation. This change adds that value to the report.
=> Add Linux ARM override value to diagnose report

agent.exs
- Wait for agent exit before reading diagnose report
- Filter out resolve DNS logs when not in debug mode
[skip review]
=> Bump agent to v-c2024bf

.changesets/only-create-root-spans-from-transaction-and-channel-action-decorators.md, lib/appsignal/instrumentation.ex, lib/appsignal/instrumentation/decorators.ex, test/appsignal/instrumentation_test.exs, test/appsignal/tracer_test.exs
Currently, because the `transaction` and `channel_action` decorators uses the `Appsignal.Instrumentation.Decorators.instrument/2` function, the decorator creates child spans when one already exist.
The `transaction` decorator exists for backward compatibility, and originally only created Transactions, which are now root spans.
This patch makes sure the decorator always creates a root span, even if another span already exists.
Closes https://github.com/appsignal/support/issues/146.
=> Transaction and channel action decorators only create root spans

.changesets/apple-arm-detection.md, mix_helpers.exs
According to support issue #150
https://github.com/appsignal/support/issues/150 the String reported by
Elixir as the system architecture is `arm-apple-darwin20.2.0` by
`:erlang.system_info(:system_architecture)`.
There are two problems with that String:
The first issue is that the `arm` String was not accounted for, only
the `aarch64` String. By adding the `arm` String we can also match ARM
architectures that report themselves as `arm`.
Secondly, it uses `arm` and not `arm64`, so we don't know which
architecture it could be. This is more of a problem for other
(non-darwin) hosts that may have 32-bit architecture. I decided not to
account for this, I don't know how, and it will fail later on in the
installation process with an architecture mismatch.
=> Fix Apple ARM detection

.changesets/bump-agent-to-0f40689.md, agent.exs
- Add Apple Darwin ARM alias.
- Improve appsignal.h documentation.
- Improve transaction debug log for errors.
- Fix agent zombie/defunct issue on containers without process reaping.
[skip review]
=> Bump agent to 0f40689

.changesets/add-support-for-telemetry-1-0-0.md, mix.exs
Add telemetry 1.0.0 as a compatible dependency.
This should be deployed after https://github.com/appsignal/appsignal-elixir-phoenix/pull/27 to avoid possible conflicts with applications that use telemetry 1.0.0.
=> Upgrade telemetry dependency

mix.exs
Mime is depended on by plug in the :test and :dev environments. CI
breaks on Elixir 1.9.4 if it picks mime 2.0.x. This patch explicitly
locks to mime ~> 1.0 on Elixir versions before 1.10.
=> Add explicit mime dependency for Elixir < 1.10

.semaphore/semaphore.yml
Update to the newer patch versions for Elixir and Erlang.
*Note*: This patch is based on #666. Please merge that first.
=> Update Elixir 1.11 and Erlang 23 versions on CI

.semaphore/semaphore.yml
Run linters and Elixir 1.11.4 on OTP 24 on CI.
*Note*: This patch is based on #667. Please merge that first.
=> Add OTP 24 to CI

.semaphore/semaphore.yml
Run Elixir 1.12.2 on OTP 24, 23 and 22.
*Note*: This patch is based on #668. Please merge that first.
=> Add Elixir 1.12.2 to CI 

.changesets/use-underscores-instead-of-slashes-in-spans-created-from-decorators.md, lib/appsignal/instrumentation/decorators.ex, test/appsignal/instrumentation_test.exs
Because the Span API uses a Span's name as what was previously described
as the event name, underscores are no longer supported.
Although this was the (documented) case before, changes in the
processing API caused this to break for people using the decorators
(which are a fallback for users upgrading from 1.0).
This patch changes the slashes in automatically generated span names to
underscores, as that's the only available alternative.
It's marked as a minor patch in the changelog, as this changes some
reported names, causing newly created incidents for insidents that
already existed before.
https://docs.appsignal.com/api/event-names.html#event-namin
Closes https://github.com/appsignal/support/issues/132
=> Replace decorator slashes with underscores

.changesets/add-mirrors-to-download-the-agent.md, agent.exs, mix_helpers.exs
Ruby integration had mirrors defined to download the agent from
different places. Now the Elixir integration has an extensible mirror
list to download the agent as well.
=> Add mirrors to download the agent

bin/setup
Using Elixir master version using sem-version command does not work.
Adding the installation before switching fixes the issue.
=> Add Elixir master download on CI

.semaphore/semaphore.yml, script/lint_git
Combine everything in one script so it's easier to maintain, the env var
with the version, the installation and running the command.
If the env vars are in the `semaphore.yml` file, it would also need to
update the `semaphore.yml` file every time you change it. It's easy to
forget, and would need multiple builds to fix.
[skip review]
=> Refactor Git lint script

bin/setup
Add the `set -e` options so that the setup script exits with a failure
if any of the commands it runs exits with a failure as well. Otherwise
it will silently fail and go unnoticed.
[skip review]
=> Fix bin/setup script, exit on failure

.changesets/fix-extension-installer-from-cached-source.md, mix_helpers.exs
In PR #671 we've added support for agent & extension downloads from
mirrors.
An edge case popped up that failed the installation. This scenario
happens when the installer fetches things from the tmp directory. When
the installer finds a matching agent & extension download in the host's
`/tmp` directory it will use that archive rather than download it again.
When it uses this installation method it does not store a `download_url`
on the `download.report` since PR #671, because it doesn't know which
mirror was originally used to download the archive. When writing the
download report it would error on the missing `download_url` key.
```
could not compile dependency :appsignal, "mix compile" failed. You can
recompile this dependency with "mix deps.compile appsignal", update it
with "mix …
```
=> Fix extension installer from tmp cached download

lib/appsignal/instrumentation.ex
I haven't actually benchmarked this :sweat_smile:, but I’m fairly sure that checking one of the two supported arities of a function in a guard is faster than getting the whole keyword list of info and so on. Plus, it's a few less lines of code!
While I got you here, I was reading through the code for `Appsignal.Instrumentation`. Would you folks appreciate some contributions to have guards on all functions and more precise function specs?
=> Speed up function arity check in Appsignal.Instrumentation

mix.exs
visiting the source link from the hosted docs are broken because of the new Git tagging format which prepends `v` at the front.
following the prophet's footstep:
https://github.com/elixir-lang/ex_doc/blame/fcfd2b9256fec710ce96d3b4a713a36cf57f34ad/mix.exs#L89
just prepend `v` in `source_ref`
=> source_ref needs 'v' prepended since tagging now has 'v' prepended

lib/appsignal/demo.ex, lib/appsignal/diagnose/agent.ex, lib/appsignal/diagnose/host.ex, lib/appsignal/diagnose/library.ex, lib/appsignal/ecto.ex, lib/appsignal/error/backend.ex, lib/appsignal/instrumentation.ex, lib/appsignal/instrumentation/decorators.ex, lib/appsignal/logger.ex, lib/appsignal/monitor.ex, lib/appsignal/probes/erlang_probe.ex, lib/appsignal/span.ex, lib/appsignal/tracer.ex, lib/appsignal/utils.ex, lib/mix/tasks/appsignal.diagnose.ex, mix.exs, mix_helpers.exs, test/support/test_agent.ex
This commit updates the version of the `credo` linter to `1.5.6`. It also addresses the new warnings given by the linter, most of which relate to the use of `Application.get_env/3` in module attributes, which are evaluated at compile time. Using `Application.compile_env/3` instead removes the warning.
Since `compile_env` is not available in Elixir versions below 1.10, a helper macro is added to `Appsignal.Utils` and used to conditionally call `get_env` or `compile_env` depending on the Elixir version.
In order to use this macro from within the `mix_helpers.exs` file, its code is duplicated within that file as `Mix.Appsignal.Utils`.
Closes #691.
=> Update `credo` to version 1.5.6

.changesets/print-dependencies-and-flags-for-install-in-diagnose-report.md, lib/mix/tasks/appsignal.diagnose.ex
The dependencies and flags fields were missing from the Elixir
integration diagnose report output. It was sent, just not printed.
Now it matches the other integrations output.
Depends on https://github.com/appsignal/diagnose_tests/pull/31
=> Print all install report fields in diagnose report

.semaphore/semaphore.yml, bin/setup
The Elixir language repository has updated the default branch to `main`,
from `master`. When kiex now tries to install the `master` branch we get
this error:
```
Unknown Elixir 'master' ☹
Try
kiex list known -- known releases
kiex list branches -- current branches
bash: pop_scope: head of shell_variables not a temporary environment scope
```
This change updates it to the new `main` default branch.
[skip review]
=> Update Elixir master to main

.changesets/fix-push-api-key-validator-request-query-params-encoding.md, .changesets/standardize-diagnose-validation-error-message.md, lib/appsignal/diagnose/validation.ex, lib/appsignal/utils/push_api_key_validator.ex, test/appsignal/utils/push_api_key_validator_test.exs, test/mix/tasks/appsignal_diagnose_test.exs, test/mix/tasks/appsignal_install_test.exs
All the other locations the transmitter is used we encode the params. If
we don't, and a parameter contains spaces, it could cause problems. I
ran into issues in the test suite not registering requests in Bypass
properly when trying to add more query params to this request.
Add the other query params to the auth request.
Update the error message to be standard for all integrations. Not all
integrations necessarily have the response status code on error, so
make sure all integrations start with "Failed to validate".
Change the validation request to a POST request, like the other
integrations. Both work, but it's good to all use the same request
method.
Add test for diagnose Push API key output and report.
Update the diagnose tests with tests for the Push API key validation in
the diagnose …
=> Standardize key validation request 

.changesets/add-scheduler-utilization-to-minutely-probes.md, lib/appsignal.ex, lib/appsignal/probes/erlang_probe.ex, lib/appsignal/probes/probes.ex, mix.exs, test/appsignal/probes/erlang_probe_test.exs, test/appsignal/probes/probes_test.exs, test/support/fake_probe.ex
This PR is part of #685. It is a re-do of #687, with an approach based on the existing, tried-and-tested Appsignal.Probes implementation. The feedback in appsignal/public_config#33 has been taken into account, and the total utilization metric has been removed.
This commit implements the Erlang scheduler utilization metric on the minutely probes.
In order to report on the scheduler utilization, the probe must keep state from its previous execution. That is, to measure the scheduler utilization between points in time A and B, you must call `:scheduler.sample/0` on point A, then pass the sample it returns to `:scheduler.utilization/1 on point B.
To be able to keep state in the probe, we keep a map of states in `Appsignal.Probes` alongside the map of probes. If a probe takes an argument, the …
=> Implement scheduler utilization metric

.changesets/remove-valid-option-from-diagnose-output.md, lib/appsignal/config.ex, test/appsignal/config_test.exs, test/appsignal/release_upgrade_test.exs, test/mix/tasks/appsignal_diagnose_test.exs
`valid` should not be a config option and should not be printed nor sent
in the diagnose report. The config initialization considers that it's
valid if there's a push api key present. Now, the validation is still
being done but not stored as a config option.
As `valid` is no longer an accessible config option, a new helper
function (`Config.valid?/0`) will tell if the configuration is valid.
=> Remove valid config opt

.changesets/push-api-key-as-an-empty-string-is-not-considered-valid-anymore.md, lib/appsignal/config.ex, test/appsignal/config_test.exs
The configuration validation will not return true anymore if the passed
push API key is an empty string.
=> Don't consider config valid if API key is empty

.changesets/fix-agent-download-openssl-below-111.md, lib/appsignal/transmitter.ex, mix_helpers.exs
Ask the SSL module for a list of supported TLS versions for Hackney to attempt to use during the agent download, so that versions that are unsupported by Elixir's currently linked "cryptolib" (that is, OpenSSL) are not listed in the `:versions` option.
This fixes #714, an issue where downloading the agent will fail when using OpenSSL 1.0.2, as the download attempts to use the TLS versions listed in `:versions` _in order_, and errors out when it attempts to use TLS 1.3, which isn't supported by the cryptolib.
The same changes to the TLS options used in the agent download are also applied to `Appsignal.Transmitter`, which is used to validate API keys and send the diagnose report.
=> Use only supported TLS versions

.changesets/bump-agent-to-v-5b63505.md, .changesets/improve-parameter-and-session-data-filtering-options.md, agent.exs, c_src/appsignal_extension.c, lib/appsignal/config.ex, lib/appsignal/nif.ex, lib/appsignal/utils/data_encoder.ex, test/appsignal/config_test.exs
Instead of using `filter_data_keys` (`_APPSIGNAL_FILTER_DATA_KEYS`) to
filter any kind of data object in the extension, split it up in the
`filter_parameters` (`_APPSIGNAL_FILTER_PARAMETERS`) and
`filter_session_data` (`_APPSIGNAL_FILTER_SESSION_DATA`) config options.
This will make it more predictable what keys are filtered out in a data
object.
Since the filtering is now done with a data object is given to the
`appsignal_set_span_sample_data` function, the
`appsignal_data_filtered_map_new` function implementation can be
removed.
This change requires an extension update for the revised configuration
behavior.
Part of https://github.com/appsignal/integration-guide/issues/31
=> Split filter parameters and session data options

lib/appsignal.ex, lib/appsignal/probes/erlang_probe.ex
The scheduler utilization sample was being obtained only after all the other metrics had been collected, and no second sample was being passed to `:scheduler.utilization`, meaning the elapsed time between samples was inconsistent. This commit modifies the Erlang probe so that the sample is collected when the probe starts, and so that the utilization is compared between the previous sample and the next.
When `:scheduler.sample/0` is called from a process for the first time, _if and only if none of its parent processes have themselves called `:scheduler.sample/0`_, the values obtained from the call will refer to the time the child process has been alive. As such, calculating the scheduler utilization from two calls obtained from different child processes returns meaningless …
=> Fix meaningless scheduler utilization values

.semaphore/semaphore.yml, bin/setup, dialyzer.ignore-warnings
When running tests on Semaphore, different combinations of Erlang/OTP versions and Elixir versions are tested. This is implemented by calling `sem-version` with the desired Erlang or Elixir version.
However, when `sem-version elixir` is called with an Elixir version that is not installed, it will install and activate the highest Erlang version supported by that Elixir version, as part of the installation process. Since `sem-version erlang` is called before `sem-version elixir`, the desired Erlang version is effectively overriden.
This commit reverses the order in which `sem-version erlang` and `sem-version elixir` are called.
When installing a given Elixir version using `sem-version elixir`, it will not directly call `kiex` to install Elixir. Instead, it will download a …
=> Fix Erlang/OTP version usage in CI

lib/appsignal/config.ex, test/appsignal/config_test.exs
We've been updating all our integrations to list and print all config
options alphabetically so they're easier to find back when looking at a
list of config options.
[skip changeset] because it's a small refactor
[skip review] because it's a small refactor
=> Sort config options alphabetically

.changesets/add-send_environment_metadata-config-option.md, lib/appsignal/config.ex, test/appsignal/config_test.exs
Allow users to enable/disable the environment metadata collection. This
is on by default.
This behavior is already implemented in the extension and agent. This
just makes it configurable for the user. No Elixir specific metadata
is currently collected.
Closes #728
For more information about this feature:
https://docs.appsignal.com/application/environment-metadata.html
=> Add send_environment_metadata config option

.changesets/fix-phoenix-filter-parameters.md, lib/appsignal/span.ex
Before this change, all sample data was passed through the `Appsignal.Utils.MapFilter.filter/1` function, which filters the given map by the allowlist specified in the `:filter_parameters` Phoenix configuration key, when it exists and is an allowlist.
This commit changes the behaviour of the `set_sample_data/3` function so that it only filters the sample data when the given key is `"params"`. This fixes #649.
=> Fix Phoenix parameter filtering

.changesets/add-scheduler-utilization-to-minutely-probes.md, .changesets/add-send_environment_metadata-config-option.md, .changesets/bump-agent-to-v-5b63505.md, .changesets/fix-agent-download-openssl-below-111.md, .changesets/fix-diagnose-report-path-modes-format.md, .changesets/fix-phoenix-filter-parameters.md, .changesets/fix-push-api-key-validator-request-query-params-encoding.md, .changesets/improve-parameter-and-session-data-filtering-options.md, .changesets/print-dependencies-and-flags-for-install-in-diagnose-report.md, .changesets/push-api-key-as-an-empty-string-is-not-considered-valid-anymore.md, .changesets/remove-valid-option-from-diagnose-output.md, .changesets/standardize-diagnose-validation-error-message.md
In the latest mono version support for changeset types were added. Newer
mono versions won't publish package changesets without types. Add these
types for existing changesets so they can be published with the latest
mono version.
[skip ci]
=> Add changeset types to existing changesets

.changesets/fix-telemetry-local-function-warning.md, lib/appsignal/ecto.ex
When a local function (meaning, either an anonymous function, or a capture of a function without the module being specified) is passed as an event handler to `:telemetry.attach/4` on Telemetry version 1.0.0, it produces a warning about the performance penalty of doing so, due to how these functions are handled by the Erlang VM.
This commit changes the event handler function passed to `:telemetry.attach/4` so that the module is specified in the function capture.
=> Fix Telemetry local function warning

.changesets/add-log_level-config-option.md, .changesets/bump-agent-to-v-0db01c2.md, .changesets/deprecate-debug-and-transaction_debug_mode-config-options.md, agent.exs, lib/appsignal/config.ex, test/appsignal/config_test.exs
This new option allows users to set up the level of severity AppSignal
logs.
PR implementing the usage of this option: appsignal/appsignal-agent#730
**WARNING**: Do not publish this change until an agent release has been done with the changes from the linked PR
=> Add log_level config option

.changesets/remove-ruby-exclusive-headers-from-request_headers-defaults.md, lib/appsignal/config.ex, test/appsignal/config_test.exs
`request_headers` list had some elements inherited from the Ruby
integration that were exclusive to `Rack`. The list is now updated and
only includes headers that make sense.
Closes #725
=> Update default request_headers list

.semaphore/semaphore.yml, mix_helpers.exs, test/appsignal/nif_test.exs
To highlight any problems of modules that could be loaded in memory. We
call `mix compile` before running the test suite. There's a need to call
`mix test` with the `--no-compile` flag otherwise it will still have the
modules from the extension installation in memory.
=> Add compilation step to CI tests

.changesets/diagnose-report-now-gets-the-agent-version-from-the-agent-file.md, lib/appsignal/diagnose/library.ex, lib/appsignal/nif.ex, test/appsignal/nif_test.exs, test/mix/tasks/appsignal_diagnose_test.exs
In the diagnose report, the agent version was obtained from the version
file that is generated after the agent installation is done.
To comply with the other integrations and to know which agent version is
being installed in the diagnose if something goes wrong, the version is
now obtained from `agent.exs` in the diagnose report.
=> Change how the agent version is retrieved for diagnose

.changesets/use-log-level-config-option-instead-of-debug.md, lib/appsignal/config.ex, test/appsignal/config_test.exs, test/appsignal/logger_test.exs
To match the changes implemented in [appsignal-agent#730][agent], the implementation of `Appsignal.Config.debug?/0`, which is in turn used by `Appsignal.Logger.debug/1`, is modified to use valid `log_level` config values as its source of truth, and fall back on the deprecated `debug` and `transaction_debug_mode` config options only if no valid `log_level` value is present.
Before this change, this method only checked the `debug` config option, not `transaction_debug_mode`. In order to be consistent with the changes to the agent (`transaction_debug_mode` implies `debug`, because a log level of "trace" implies "debug") this method now checks `transaction_debug_mode` as well.
Fixes #746.
[agent]: https://github.com/appsignal/appsignal-agent/pull/730/
=> Use `log_level` instead of `debug`

.changesets/add-send_session_data-config-option.md, .changesets/deprecate-skip_session_data-config-option.md, lib/appsignal/config.ex, test/appsignal/config_test.exs
This replaces the `skip_session_data` option that is now deprecated.
As discussed in https://github.com/appsignal/integration-guide/pull/114
the `skip_session_data` is inconsistently named compared to our other
options that do the same thing, but start with `send_`.
The behavior of `send_session_data` is also the exact opposite of
`skip_session_data`. It's on by default and if turned off it won't send
the session data.
Only when `send_session_data` is not set by the user, will
`skip_session_data` be listened to. If `send_session_data`'s value is
determined by the `skip_session_data_backwards_compatibility` method,
its value is set in the `system` source, because the system figured
out what value it needs to be set to. If the user has manually
configured it, it will not set it in the …
=> Add send_session_data config option

.semaphore/semaphore.yml, mix.exs, test/appsignal/error/backend_test.exs, test/appsignal/transmitter_test.exs
This PR must be rebased against `main` after #718 is merged.  The CI checks currently do not pass for the following reason:
This commit adds back CI checks for OTP 20 on Elixir 1.9.
The integration compiles successfully when the Telemtry dependency version is set to `~> 0.4`, instead of to `~> 0.4 or ~> 1.0`.
=> Fix OTP 20 tests

.changesets/add-config-override-source.md, lib/appsignal/config.ex, lib/mix/tasks/appsignal.diagnose.ex, test/appsignal/config_test.exs
I saw a warning about an unused variable in the test so I removed it.
When a config option is set by the integration based on other config
options, the new config option values are written to the "override"
source.
This may happen for renamed config options that set the new config
option when the deprecated config option is set, like the
`skip_session_data` and `send_session_data` config options this commit
updates to this new source.
This "override" config source is leading. It should not be confused with
"system" that determines _defaults_ for the config based on environment
details like host and system (not AppSignal environment variables).
I've changed the order how the config sources and options are loaded in
the code, sources are only written to the `Application` env at the very …
=> Add "override" config source

.semaphore/semaphore.yml, test/appsignal/error_test.exs, test/appsignal/span_test.exs
Add the latest Elixir version along with OTP 24.2
OTP 24.2 adds additional info to `ArgumentError` messages. This commit modifies the tests, so they pass no matter the OTP version.
---
I decided to ignore the message in the span tests as it is not so relevant for those two examples. If you think it's important enough to assert it, tell me, and I'll update it to check each value from the tuple that `Test.Nif.get!(:add_span_error)` returns.
Fixes: #757
=> Elixir ci 1.13.2

test/support/fake_erlang.ex
Only mock the key we need to mock. This way any other values we ask from
`:erlang.system_info/1` isn't always the same host triple.
When something other than `:system_architecture` is asked, return the
real value.
=> Don't mock all of :erlang.system_info/1 in tests

.changesets/prevent-extension-installation-failure-when-cacert-is-not-accessible.md, mix_helpers.exs
The extension installation will no longer fail if the CA cert file is
not accessible. It'll print a warning and use the library defaults.
Fixes: #756
=> Check CAcert file exists when installing extension

lib/appsignal/tracer.ex, test/appsignal/tracer_test.exs
`Tracer.ignore_process/0` can only ignore current pid.
I want to make Tracer also ignore another pid (see: https://github.com/appsignal/appsignal-elixir/pull/549)
=> Tracer can ignore a specific process

.changesets/don't-set-parameters-when-the-send_params-configuration-is-set-to-false.md, lib/appsignal/span.ex, test/appsignal/span_test.exs
Currently, the send_params configuration option is checked in [Appsignal.Plug.set_params/2-3](https://github.com/appsignal/appsignal-elixir-plug/blob/main/lib/appsignal_plug.ex#L168-L179).
Since parameters are now also added from appsignal_phoenix, and because there's already a distinction between sample data and parameters in Appsignal.Span, Appsignal.Span.set_sample_data/3-4 now checks the send_params configuration if the passed key equals "params".
The implementation in appsignal_plug can be removed as soon as it depends on the upcoming version of this library.
=> Don't set params when send_params is false

.changesets/don't-set-session-data-when-the-send_session_data-configuration-is-set-to-false.md, lib/appsignal/span.ex, test/appsignal/span_test.exs
Note: this is the same patch as 96c60363b06f64ed43b1f8a88484ecde45c1710a, but for session data.
Currently, the send_session_data configuration option is checked in [Appsignal.Plug.set_session_data/2-3](https://github.com/appsignal/appsignal-elixir-plug/blob/main/lib/appsignal_plug.ex#L168-L179).
Since sesion data is now also added from appsignal_phoenix, and because there's already a distinction between sample data and parameters in Appsignal.Span, Appsignal.Span.set_sample_data/3-4 now checks the send_session_data configuration if the passed key equals "sesion_data".
The implementation in appsignal_plug can be removed as soon as it depends on the upcoming version of this library.
=> Don't set session when send_session_data is false

.changesets/fix-compile-time-error-with-empty-configurations.md, lib/appsignal/config.ex, test/appsignal/config_test.exs, test/support/utils.ex
This is based on https://github.com/appsignal/appsignal-elixir/pull/774, in which @tonyvanriet fixed a compile-time error when the `Appsignal.Config.log_level/0` function was called without a config present. This patch adds a regression test and a changeset.
=> Use default log level when AppSignal is not configured

.changesets/don-t-crash-at-compile-time-when-appsignal-is-not-configured.md, lib/appsignal/config.ex, test/appsignal/config_test.exs
After the `without_config/0` option was added in #775, I went over the configuration options that use `Application.fetch_env!/2`, added tests to make sure they function without any configuration loaded, and switched them over to `Application.get_env/3`.
=> Handle empty configurations for all config options

.changesets/improve-error-message-on-extension-load-failure.md, config/config.exs, dialyzer.ignore-warnings, lib/appsignal.ex, mix_helpers.exs, test/appsignal/appsignal_test.exs, test/support/fake_os.ex
It's a common problem for apps first installed on the host system
(macOS) and then mounted with the `deps` and `_build` directory in a
Docker container that's running another Operating System like Ubuntu to
not start the extension. This is because the extension is not installed
for the container's architecture.
If the target and architecture mismatch, print the installed and current
target and architecture so users can spot the difference between them.
This will hopefully make the error more clear: the user needs to
reinstall the extension for their host's architecture.
Closes #254
This error message will be printed on the start of the AppSignal
application and not on compilation. On compilation it will still print
the generic message:
> Error loading NIF (Is your operating system …
=> Improve error reporting on extension load failure

.changesets/bump-agent-to-v-d573c9b.md, agent.exs
- Clean up payload storage before sending. Should fix issues with
locally queued payloads blocking data from being sent.
- Add OpenTelemetry support for the Span API. Not currently implemented
in this package's extension.
[skip review]
=> Bump agent to v-d573c9b

Makefile
The local install files are stored in `c_src/` directory. Running `make
clean` did not clean this and that is what I expect from the clean
command.
=> Update make clean to also clean c_src directory

.changesets/always-return-the-span-from-span-set_attribute-3.md, lib/appsignal/span.ex, test/appsignal/span_test.exs
Previously, the Span.set_attribute/3 function returned nil when
non accepted values (like nil) were passed in the rescue clause.
Instead, this patch makes sure to always return the span.
=> Always return the span from set_attribute/3 and set_sql/3

.changesets/bump-agent-06391fb.md, agent.exs
- Accept "warning" value for the `log_level` config option.
- Add aarch64 Linux musl build.
- Improve debug logging from the extension.
- Fix high CPU issue for appsignal-agent when nothing could be read from
the socket.
[skip review]
=> Bump agent to 06391fb

.changesets/always-return--ok-from-appsignal-config_change-3.md, dialyzer.ignore-warnings, lib/appsignal.ex, lib/appsignal/logger.ex, test/appsignal/release_upgrade_test.exs
In some situations, Appsignal.config_change/3 didn’t produce the expected `:ok` response. This patch makes sure it always does. It also includes fixes and type specs for the Logger, which also didn’t always return the expected `:ok`
Closes #779.
=> Always return :ok from Appsignal.config_change/3

.changesets/always-return-the-span-from-span-setter-functions--to-allow-for-chaining-setter-calls-with-optional-values.md, lib/appsignal/span.ex, test/appsignal/span_test.exs
The set_name/2, set_namespace/2 and set_sample_data/3 functions all had
a rescue clause that returned a nil value, even if a span was passed to
them.
This caused issues with optional arguments, where a value that should be
a string was a nil. Instead of returning the span unchanged (which is
expected when chainging functions), these functions would then return a
nil, breaking the setters for the rest of the chain.
This patch makes sure the span is returned as passed, if it's a nil or a
proper span.
=> Always return the span from Span setter functions

.changesets/fix-compile-time-warning-about-unused-funtion-in-extension.md, c_src/appsignal_extension.c
Hooks up _set_span_attribute_sql_string. Although Ecto and :telemetry report queries with the sensitive data stripped out, meaning AppSignal's SQL sanitizer doesn't have anything left to do, this patch properly hooks up _set_span_attribute_sql_string to call the function _with_ SQL sanitization.
This fixes a compile-time warning and makes the implementation of the Ecto integration behave as promised, theoretically.
=> Fix warning about an unused funtion in extension

.changesets/fix-extension-link-new-xcode-tools.md, Makefile
We ran into an issue with the new Xcode version 14 command line tools, version 2395.
The linker gave a warning about `dynamic_lookup` not working with chained fixups, a thing that is now enabled by default on the command line tools looks like.
```
ld: warning: -undefined dynamic_lookup may not work with chained fixups
```
It looks like we can't use `dynamic_lookup`. Instead define a list ourselves of all the symbols we use in the `c_src/appsignal_extension.c` file. That way we tell the linker to ignore the undefined symbols, and have them be looked up at runtime when the Elixir NIF library is loaded. Every time we call another NIF function defined in `erl_nif.h` we need to update this list.
Xcode Version 13.4.1 (13F100), from macOS 12.5:
```
$ man ld
-undefined treatment
Specifies how …
```
=> Explicitly define used NIF symbols

.changesets/fix-extension-symbol-definitions.md, Makefile
We made a mistake in PR #792. We split up the very long line in the Makefile to specify a symbol per line. This accidentally broke how the linker interprets these options.
Specify the symbols per line, but on each line also include the `-Wl,` prefix to specify the linker option. Somehow the multi line option value for `-Wl,` didn't work.
=> Fix undefined symbols specified for linking

.changesets/fix-extension-linking-on-alpine-linux-arm64-systems.md, Makefile
The extension linking failed on symbols being defined multiple times. This is because the Rust compiler includes the `__fe_getround` `__fe_raise_inexact` [symbols for ARM64 targets][symbols].
I couldn't find a way to mark either symbol as "weak", so it would be overridden with the other "strong" symbol. I couldn't find a way to mark them as weak outside of their original definition.
Instead this change allows symbols to be defined multiple times. As per the GNU libc [documentation of this linker flag][ld man], it will only use the first defined symbol. (I link to the GNU linker docs, because I can't find the musl linker docs.)
> --allow-multiple-definition
> -z muldefs
>   Normally when a symbol is defined multiple times, the linker will
>   report a fatal error. These options allow …
=> Fix Alpine Linux ARM64 extension linking

.changesets/add-finch-integration.md, lib/appsignal.ex, lib/appsignal/finch.ex, test/appsignal/finch_test.exs
As requested [through support](https://github.com/appsignal/support/issues/216). This patch adds support for Finch, the HTTP client by listening for the `[:finch, :request, :start]` and `[:finch, :request, :stop]` messages sent through :telemetry.
=> Add Finch integration

.changesets/fix-functionclauseerror-for-old-finch-versions.md, lib/appsignal/finch.ex, test/appsignal/finch_test.exs
Finch 0.11 and below report `telemetry` events with the same name as those by Finch 0.12 and above, but the events carry different meanings and the metadata map provided has a different structure.
Due to the different structure of the metadata map, our event handlers resulted in a `FunctionClauseError`, causing the handlers to detach.
This commit changes the event handlers so that events not matching the expected structure are silently ignored. This means that we do not break applications using Finch 0.11 and below, but those Finch versions remain unsupported by our Finch integration.
Fixes #797.
=> Fix FunctionClauseError for Finch <0.12

mix.exs
Newer plug versions (starting 1.14) require Elixir 1.10 to work. This commit fixes the plug version to the latest 1.13 for older Elixir versions.
=> Fix plug dependency for Elixir 1.9

.changesets/logging-support.md, agent.exs, c_src/appsignal_extension.c, lib/appsignal.ex, lib/appsignal/config.ex, lib/appsignal/ecto.ex, lib/appsignal/error/backend.ex, lib/appsignal/finch.ex, lib/appsignal/integration_logger.ex, lib/appsignal/logger.ex, lib/appsignal/monitor.ex, lib/appsignal/nif.ex, test/appsignal/config_test.exs, test/appsignal/integration_logger_test.exs, test/appsignal/logger_test.exs, test/support/appsignal/test_nif.ex
In order to implement the Logger that comunicates with the Logging API
in the agent, the integration internal logger is renamed to Integration
Logger. This is based in the Ruby and Node.js implementation.
This module exposes functions to log messages by severity through the
extension Logging API
This option tells the agent where to send the logs made through its API.
Adds the diagnose tests updated submodule with support for the
`logging_endpoint` config option.
Closes #799
=> Logging feature

.changesets/replace-arguments-in-stack-traces-with-sanitized-versions-instead-of-stripping-them-out-completely.md, lib/appsignal/stacktrace.ex, lib/appsignal/utils/argument_cleaner.ex, lib/appsignal/utils/type.ex, test/appsignal/stacktrace_test.exs, test/appsignal/utils/argument_cleaner_test.exs, test/appsignal/utils/type_test.exs
Instead of stripping out arguments from exceptions like `UndefinedFunctionError`s, this patch replaces the arguments with their types where required.
For example, a string (like `”foo”`) is replaced with `binary`. Types like integers aren’t replaced, as they don’t pose a threat to expose sensitive data. For maps and structs, the values are stripped out, but their keys aren’t.
Closes https://github.com/appsignal/support/issues/221.
[skip blogpost]
=> Stack trace argument types

.changesets/add-enable_error_backend-configuration-option.md, lib/appsignal.ex, lib/appsignal/config.ex, lib/appsignal/error/backend.ex, test/appsignal/config_test.exs, test/appsignal/error/backend_test.exs
In order to allow users to disable the error backend, which has now been replaced by our integrations, this patch adds a configuration option. By default, the backend is enabled, to not change the current functionality.
Users who get double or unneeded errors reported in the background namespace can disable the error backend. The error backend will be disabled by default in a future version before it's removed altogether in the next major release.
Part of https://github.com/appsignal/support/issues/222.
=> Add error_backend_enabled configuration option

.changesets/fix-argument-cleaner-pid-issue.md, lib/appsignal/utils/argument_cleaner.ex, test/appsignal/stacktrace_test.exs, test/appsignal/utils/argument_cleaner_test.exs
Fixes an issue when an exception is raised on a function call whose arguments contain a map of PIDs. ([Slack](https://appsignal.slack.com/archives/CNPP953E2/p1669702081071889), [Intercom](https://app.intercom.com/a/inbox/yzor8gyw/inbox/admin/4356044/conversation/16410700160759?view=List))
Some values that are left "as-is" when cleaned do not implement `String.Chars`. Since the `Type` struct implements both `Inspect` and `String.Chars`, call `inspect` on the cleaned value.
=> Fix argument cleaner PID issue

.changesets/fix-hackney-issue-with-metrics-configuration-during-install.md, mix_helpers.exs
Users may configure Hackney to report metrics to a separate module. However, that module will not be loaded during the installation Mix task, causing Hackney to error. This change unsets the configuration key that defines the module to report metrics to.
Fixes #802.
---
Thanks for the fix suggestion @arjan!
=> Unset Hackney metrics config during install

.changesets/track-the-operating-system-release-distro-in-the-diagnose-report.md, lib/appsignal/diagnose/host.ex, test/mix/tasks/appsignal_diagnose_test.exs
This helps us with debugging what exact version of Linux an app is running on, for example.
Part of https://github.com/appsignal/support/issues/206
Test failures are unrelated.
=> Track OS distro in diagnose report

lib/appsignal.ex, lib/appsignal/oban.ex, lib/appsignal/probes/erlang_probe.ex, lib/appsignal/utils/hostname.ex, test/appsignal/oban_test.exs, test/appsignal/probes/erlang_probe_test.exs, test/support/appsignal/fake_appsignal.ex
Part of #805. See appsignal/test-setups#78 for a test setup. [skip blogpost]
---
Instrument the `[:oban, :engine, :insert_job, ...]` telemetry span events and create an AppSignal child span with data about the job inserted. Use the worker name as the span name, if available.
Instrument the `[:oban, :job, ...]` telemetry span-like events and create an AppSignal root span with data about the job being processed. Use the arguments given to the job as params, and set useful attributes of the job, such as its ID, the queue, the attempt number, its priority and the execution result, as tags. Use the job worker as the name of the root span.
Set an error for the `[:oban, :job, :exception]` event.
Track a distribution gauge for the job duration, by worker, and for each worker by state.
Track a …
=> Add Oban instrumentation

.changesets/add-nginx-metrics-support.md, agent.exs, lib/appsignal/config.ex, test/appsignal/config_test.exs
Update the diagnose tests to expect the config option.
These options should've been passed to the agent before, but weren't.
Update the agent to a version that supports NGINX metrics.
=> Add NGINX metrics support

.changesets/add-metadata-functions-for-plug-phoenix-apps.md, lib/appsignal/metadata.ex
The metadata function in the Plug integration now includes a name, category, params and session data. This patch is part of the work needed for https://github.com/appsignal/appsignal-elixir-phoenix/issues/57.
=> Add metadata functions for Plug/Phoenix libraries

.changesets/disable-instrumentations.md, .changesets/fix-enable-error-backend.md, .changesets/report-oban-errors.md, lib/appsignal.ex, lib/appsignal/config.ex, lib/appsignal/ecto.ex, lib/appsignal/oban.ex, test/appsignal/config_test.exs, test/appsignal/ecto_test.exs, test/appsignal/finch_test.exs, test/appsignal/oban_test.exs
Fixes appsignal/feature-requests#97.
Add the `instrument_ecto`, `instrument_finch` and `instrument_oban`
config options to disable the automatic Telemetry instrumentations.
Adds a config option that determines when Oban jobs report errors.
When set to `none`, no errors from exception events will be
reported. When set to `all`, all errors from exception events will
be reported. When set to `discard`, errors from exception events
will be reported if the state of the job has been set to `discard`.
If the `:state` metadata key is not present (v2.3.1 and below) then
`discard` will behave like `all`, assuming each event to be
discarded.
Change the behaviour of `Appsignal.Oban.attach/0` to deattach
existing handlers before attaching new handlers. This allows the
config option to be read only …
=> Add `report_oban_errors` config option

test/appsignal/diagnose/report_test.exs
One of the error scenarios in the diagnose reports is when an unexpected error occurs. In the tests, this is simulated by taking the test diagnose server down, resulting in a :econnrefused.
In some situations, the error thrown is a :closed, which made this test brittle. To fix that, the test no longer explicitly tests for a :econnrefused. Rather, it just tests if an error with a reason key is returned when this happens.
This fixes the brittleness in the ReportTest, as shown in the [brittle](https://appsignal.semaphoreci.com/branches/f2dc647d-3c7d-45b7-8641-9b4916196050) branch, from which this fix is extracted.
=> Don't match econnrefused in ReportTest exactly

test/appsignal/monitor_test.exs
This pull request removes a complicated and unnecessary test, and updates a test with an assertion that’s too specific. Together, they fix the brittleness in the MonitorTest, as shown in the [brittle](https://appsignal.semaphoreci.com/branches/f2dc647d-3c7d-45b7-8641-9b4916196050) branch, from which these fixes are extracted.
=> Update MonitorTest to fix brittleness

test/appsignal/diagnose/paths_test.exs
Instead of making sure the contents of the files match exactly, check the length, which is what the test is actually asserting.
This fixes the brittleness in the PathsTest, as shown in the [brittle](https://appsignal.semaphoreci.com/branches/f2dc647d-3c7d-45b7-8641-9b4916196050) branch, from which this fix is extracted.
=> Only test log length in PathsTest

lib/appsignal/probes/erlang_probe.ex, test/appsignal/probes/erlang_probe_test.exs, test/appsignal/probes/probes_test.exs, test/support/utils.ex
This patch reimplements the ErlangProbe tests, so they’re no longer dependent on the FakeAppsignal module, which caused issues in the past. The implementation now exposes `metrics/2`, which is then tested on. 
This does leave a gap between extracting the data and actually sending it to the extension, which we used to do using the `FakeAppsignal` module. Aside from that, everything that was tested previously is present in the new tests.
This fixes the brittleness in the ErlangProbeTest, as shown in the [brittle](https://appsignal.semaphoreci.com/branches/f2dc647d-3c7d-45b7-8641-9b4916196050) branch, from which these fixes are extracted.
=> Reimplement ErlangProbe tests

test/appsignal/oban_test.exs
This patch fixes the brittleness in the ObanTest, as shown in the [brittle](https://appsignal.semaphoreci.com/branches/f2dc647d-3c7d-45b7-8641-9b4916196050) branch, from which these fixes are extracted.
=> Fix brittleness in Oban tests

.changesets/bump-agent-to-8d042e2.md, agent.exs, c_src/appsignal_extension.c
Use latest agent build with an extra argument for format. Unused in the Elixir integration at the moment.
=> Hardcode log format to plaintext

.changesets/add-logger-backend.md, lib/appsignal/logger.ex, lib/appsignal/logger/backend.ex, test/appsignal/logger/backend_test.exs, test/appsignal/logger_test.exs
With the new logger backend, users can redirect their logs to AppSignal by attaching the backend in their application.ex files:
``` elixir
Logger.add_backend({Appsignal.Logger.Backend, [group: "phoenix"]})
```
Closes #800.
=> Logger backend

lib/mix/tasks/appsignal.diagnose.ex
Maps over 32 items drop their ordering, so this patch explicitly orders items before printing them.
Part of #834.
=> Explicitly order configuration options in diagnose

.changesets/handle-unexpected-events-in-logger-backend.md, lib/appsignal/logger/backend.ex, test/appsignal/error/backend_test.exs
As reported in #836, the error backend crashes when it receives an unexpected event. This patch adds a catch all so these events call a noop.
To test this, switch your appsignal dependency to the `logger-backend-error` branch:
``` elixir
{:appsignal, github: "appsignal/appsignal-elixir", branch: "logger-backend-error", override: true},
```
=> Handle unexpected events in Error.Backend

.changesets/update-agent-6f29190.md, agent.exs, lib/appsignal/config.ex, test/appsignal/config_test.exs
Rename the internal APPSIGNAL_ENVIRONMENT env var to the publicly known
APPSIGNAL_APP_ENV env var.
This makes all the agent config options consistent with each other.
[skip changeset] because it requires an agent update that will include
a changeset.
- Log revision config in boot debug log.
- Update internal agent CLI start command.
- Rename internal `_APPSIGNAL_ENVIRONMENT` variable to
`_APPSIGNAL_APP_ENV` to be consistent with the public version.
=> Update agent to version 6f29190

.changesets/add-absinthe-instrumentation.md, CHANGELOG.md, lib/appsignal.ex, lib/appsignal/absinthe.ex, lib/appsignal/config.ex, mix.exs, test/appsignal/absinthe_test.exs, test/appsignal/config_test.exs
This patch adds Absinthe support to the Elixir integration.
On its own, this will automatically create spans for Absinthe executions. Combined with https://github.com/appsignal/appsignal-elixir-phoenix/pull/67, this patch should automatically create spans for requests to the Absinthe endpoint with the executions wrapped in a span.
This patch is intended to replace the [absinthe snippet we used to have in our documentation](https://github.com/appsignal/appsignal-docs/blob/a6a865ef2dedbf39a6786bd986a864a1051d0373/source/elixir/integrations/absinthe.html.md).
Closes #751.
=> Absinthe instrumentation

.changesets/add-absinthe-instrumentation.md, CHANGELOG.md, lib/appsignal.ex, lib/appsignal/absinthe.ex, lib/appsignal/config.ex, mix.exs, test/appsignal/absinthe_test.exs, test/appsignal/config_test.exs
Continuation of https://github.com/appsignal/appsignal-elixir/pull/834, which wasn’t supposed to be released yet, as we’re still working on documentation. Consider this a tracking issue.
[skip-review]
=> Absinthe support

.changesets/trim-sql-attributes-in-spans.md, agent.exs
This includes a fix for the `set_attribute_sql_string` to truncate very long SQL strings, preventing very big payload sizes.
=> Bump agent to version 6ac961d

.changesets/bump-agent-to-fd8ee9e.md, .changesets/statsd-port-config-option.md, agent.exs, lib/appsignal/config.ex, test/appsignal/config_test.exs
Allow configuration of the agent's statsd server port through the statsd_port option.
Requires an agent update from https://github.com/appsignal/appsignal-agent/pull/995
- Rely on APPSIGNAL_RUNNING_IN_CONTAINER config option value before
other environment factors to determine if the app is running in a
container.
- Fix container detection for hosts running Docker itself.
- Add APPSIGNAL_STATSD_PORT config option.
=> Add statsd_port config option

.changesets/add-tesla-integration.md, lib/appsignal.ex, lib/appsignal/config.ex, lib/appsignal/finch.ex, lib/appsignal/tesla.ex, test/appsignal/config_test.exs, test/appsignal/finch_test.exs, test/appsignal/tesla_test.exs
Part of https://github.com/appsignal/support/issues/257. See [test setup](https://github.com/appsignal/test-setups/pull/113) and [server changes](https://github.com/appsignal/appsignal-server/pull/9562) and [diagnose changes](https://github.com/appsignal/diagnose_tests/pull/87).
Implement an instrumentation for the Tesla HTTP client library, based on our existing Finch instrumentation.
If the Tesla.Middleware.PathParams middleware is used, a template is used as the URL, and parameters are passed separately, to be interpolated by this middleware. If the instrumentation detects that the PathParams middleware is being used correctly, it will send the template URL as part of the sanitised URL. Otherwise, it will only send the scheme, host and port of the URL.
If the Tesla.Middleware.BaseUrl …
=> Implement Tesla instrumentation

.changesets/add-handling-for-cowboy-error-edge-cases-to-prevent-error-backend-crashes.md, lib/appsignal/error/backend.ex, lib/appsignal/stacktrace.ex, test/appsignal/error/backend_test.exs, test/appsignal/stacktrace_test.exs
Previously, the handle_report/1 function checked if the report had a
:cowboy domain, but only if there was no conn included in the
report. This patch fixes that, to make sure all cowboy reports are
filtered out.
Closes https://github.com/appsignal/appsignal-elixir/issues/850.
=> Never register cowboy error reports

.changesets/improve-tracer-performance-by-removing-duplicate-runtime-configuration-and-storage-checks.md, lib/appsignal/config.ex, lib/appsignal/span.ex, lib/appsignal/tracer.ex, test/appsignal/span_test.exs
As reported in https://github.com/appsignal/appsignal-elixir/issues/845, the instrumentation helper did some unnecessary reductions. This pull request is the result of looking into the reductions report and removing some defensive programming we didn't really need, _without_ changing any functionality.
Elixir's `profile.eprof` mix task evaluates a piece of code with the [eprof](https://www.erlang.org/doc/man/eprof.html) profiling tool enabled. After running the code, it outputs a time profile report, which shoes the number of calls to each function, as well as the amount of time spent in each.
To look into the `Appsignal.Instrumentation.instrument/3` function, we evaluated the following code snippet through the eprof task:
```shell
mix profile.eprof -e "(1..1_000) |> Enum.each(fn _ -> …
```
=> Reduce number of reductions in Appsignal.Instrumentation.instrument/3

Dockerfile, README.md, c_src/appsignal_extension.c, spans.exs
This patch adds a testing setup to a script that calls Nif functions on a build with AddressSanitizer enabled. Although we didn't find any memory issues in any current version of the integration, this setup is useful to ensure we don't add memory problems in the future.
It's currently implemented like the benchmarking scripts, meaning it's not integrated in CI. I think running this on CI would be useful as well, but I'm unsure how that would work, as the whole test setup runs from a Docker container.
=> Add AddressSanitizer test setup

.changesets/add-set-sample-data-if-nil-function.md, agent.exs, c_src/appsignal_extension.c, lib/appsignal/nif.ex, lib/appsignal/span.ex, lib/appsignal/test/span.ex, test/appsignal/span_test.exs
Part of https://github.com/appsignal/appsignal-elixir/issues/862.
See also [agent PR](https://github.com/appsignal/appsignal-agent/pull/1018) -- if there are changes in that PR, the agent version bundled in this PR at the time of writing this might need to be updated.
---
Update the agent to a version where `set_span_sample_data_if_nil` is implemented, and implement the `set_sample_data_if_nil` function for `Appsignal.Span`.
=> Implement `set_sample_data_if_nil` method

.changesets/use-render_git_commit-as-revision.md, CHANGELOG.md
See also appsignal/appsignal-docs#1370, which should have `since_notes` with the versions in which this behaviour was added.
---
Add a changeset entry for `RENDER_GIT_COMMIT` support. Support was added in the previous release, but not documented in the changelog.
(see: [elixir commit that updated the agent](https://github.com/appsignal/appsignal-elixir/commit/be41143553a8d6a37e2af12e688f5625cb1d3de8), [agent commits in release that it was updated to](https://github.com/appsignal/appsignal-agent/commits/v-9e1ad6b))
=> Add `RENDER_GIT_COMMIT` changeset

.changesets/bump-agent-to-32590eb.md, agent.exs
- Only ignore disk metrics that start with "loop", not all mounted disks that end with a number to report metrics for more disks.
[skip review]
=> Bump agent to 32590eb

.changesets/allow-json-and-logfmt-log-messages.md, lib/appsignal/logger.ex, test/appsignal/logger_test.exs
Instead of passing metadata to the convenience methods, a format can be passed which will be used to parse metadata out of the message in the Logfmt or JSON format.
Fixes appsignal/support#244.
=> Allow JSON and Logfmt log messages

dialyzer.ignore-warnings, lib/appsignal/diagnose/agent.ex
The agent and extension no longer needs these env vars. It works without it, because it now tell the agent to run the diagnose command by using the `appsignal-agent diagnose` subcommand (as called by the extension).
I came across this when taking a brief look at the related dialyzer issues reported in #853.
Update dialyzer warning because the stacktrace changed.
[skip changeset] because it's a small internal refactor.
=> Remove unneeded _APPSIGNAL_DIAGNOSE env vars

.changesets/report-total-cpu-usage-metric-for-vms.md, agent.exs
This change adds another `state` tag value on the `cpu` metric called `total_usage`, which reports the VM's total CPU usage in percentages.
Part of https://github.com/appsignal/probes-rs/issues/64
[skip review]
=> Report total CPU usage host metric for VMs

lib/appsignal/instrumentation/decorators.ex, test/appsignal/instrumentation_test.exs
Before this fix atom values in the transaction_event decorator were ignored because of the `is_binary(key)` guards and this pokemon clause: https://github.com/appsignal/appsignal-elixir/blob/main/lib/appsignal/span.ex#L168.
I am not sure why the pokemon clause but I would suggest removing it since it will hide bugs like this. Let me know if you want a separate PR for that.
=> Fix atoms in transaction_event decorator

.changesets/bump-agent-to-6bec691.md, agent.exs
- Upgrade `sql_lexer` to v0.9.5. It adds sanitization support for the `THEN` and `ELSE` logical operators.
[skip review]
=> Bump agent to 6bec691

dialyzer.ignore-warnings, lib/appsignal/diagnose/agent.ex
Explicitly casting the NIF's diagnose return type to string makes dialyzer happy in 1.15.
---
This is clearly a hack-ish workaround. Couldn't get a better solution for it. Another option would be to make the `_diagnose` function from the unloaded NIF return other than an atom, but I think this PR's implementation is cleaner.
Fixes: #853 
=> Add string cast to agent diagnose

.changesets/bump-agent-d789895.md, agent.exs
- Increase short data truncation from 2000 to 10000 characters.
[skip review]
=> Bump agent to version d789895

.changesets/add-role-config-option.md, lib/appsignal/config.ex, test/appsignal/config_test.exs
Allow users to configure a role for a host. It's not used a lot in the product yet, but we generate a metric for it and we can do some more stuff with it in the future.
Part of https://github.com/appsignal/appsignal-agent/issues/1020
=> Add host_role config option

mix.exs
Newer versions of Dialyxir use the
[Kernel.then/2](https://hexdocs.pm/elixir/Kernel.html#then/2) syntax introduced in Elixir 1.12.
Lock the package to 1.3, so we can run it on older versions while we still support them.
See also #881 for dropping those older versions.
=> Lock Dialyxir to 1.3 for older Elixir versions

.changesets/bump-agent-to-6133900.md, agent.exs
- Fix `disk_inodes_usage` metric name format to not be interpreted as a JSON object.
[skip review]
=> Bump agent to 6133900

mix.exs
It fails to build the `parse_trans` package on OTP < 21, because Hackney bumped its version lock between package version 1.18.1 and 1.18.2. The newer `parse_trans` version requires OTP > 21.
[skip review]
=> Fix build by locking Hackney on OTP < 21

.changesets/bump-agent-to-e8207c1.md, agent.exs
- Add `memory_in_percentages` and `swap_in_percentages` host metrics that represents metrics in percentages.
- Ignore `/snap/` disk mountpoints.
- Fix issue with the open span count in logs being logged as a negative number.
- Fix agent's TCP server getting stuck when two requests are made within the same fraction of a second.
[skip review]
=> Bump agent to e8207c1

lib/appsignal/tracer.ex, test/appsignal/tracer_test.exs
Taking over #894 to implement our little bikesheds about it. (ping @zachdaniel for visibility)
Add `register_current/1` to `Appsignal.Tracer`. This is needed by the `ash_appsignal` instrumentation, as Ash starts processes for you.
[skip changeset] as it is `@doc false`
=> Allow passing the current span across processes

.changesets/avoid-creating-oban-insert-job-root-span.md, lib/appsignal/oban.ex, test/appsignal/oban_test.exs
Only emit the "insert job" event if there is a current parent span. Fixes #890.
=> Do not create insert job root span

.changesets/bump-agent-to-b604345.md, agent.exs
Include changelog notes for this release, but not release 8260fa1 as it was OpenTelemetry specific, which the Elixir package doesn't support.
[skip review]
=> Bump agent to b604345

.changesets/bump-agent-1dd2a18.md, agent.exs
- When adding an SQL body attribute via the extension, instead of truncating the body first and sanitising it later, sanitise it first and truncate it later. This prevents an issue where queries containing very big values result in truncated sanitisations.
[skip review]
=> Bump agent to 1dd2a18

.changesets/improve-ecto-transaction-instrumentation.md, lib/appsignal/ecto.ex, test/appsignal/ecto_test.exs
Instead of discarding `begin` and `commit` queries, use them as the start and end point of a parent span that groups the transaction.
Handle `rollback` queries as well by adding them to this transaction group, quickly showing at a glance whether the transaction succeeded or failed.
=> Improve `Ecto.Multi` instrumentation

.changesets/error-metrics.md, agent.exs
Fixes issue with error metrics for apps like Node.js Koa. Could affect Elixir spans as well.
[skip review]
=> Bump agent to 8f31b1a

test/appsignal/nif_test.exs, test/support/utils.ex
Suddenly breaks the build, so let's fix it by renaming the function in the way Credo suggests.
[skip review]
=> Fix Credo issue about function naming

.changesets/remove-deprecated-extension-functions.md, .changesets/update-probes-0.5.4.md, agent.exs
- Remove deprecated extension functions.
- Update probes library with fix for Alpine Linux disk usage stats.
[skip review]
=> Bump agent to bfe19b1

.changesets/fix-data-encoding-for-keyword-lists.md, .changesets/support-lists-as-root-sample-data.md, lib/appsignal/span.ex, lib/appsignal/utils/data_encoder.ex, test/appsignal/span_test.exs, test/appsignal/utils/data_encoder_test.exs
Add a test case for a previously failing scenario encoding keyword lists.
Implement encoding for this by checking if a list is a keyword list, then casting each item from a Tuple to a List, so the item is not interpreted as a thing we can set on a Map.
If it encounters a keyword list's Tuple, it assumed the parent would be a Map, and try to set it on the non-existent map. Then the Rust Extension's data encoder would silently drop the value.
We documented that we support lists as sample data root values, but in practice we did not.
This fix allows for setting lists as custom sample data (and other types of sample data) as shown in the changeset.
---
- [Intercom conversation](https://app.intercom.com/a/inbox/yzor8gyw/inbox/admin/540709/conversation/16410700282572?view=List)
=> Sample data fixes for lists and keyword lists

test/mix/tasks/appsignal_diagnose_test.exs
Ran into this earlier while testing #911 locally.
The order of map keys returned by `Map.keys` is not guaranteed. This test fails sometimes when running locally (although somewhat surprisingly it's very rare)
=> Fix flickering assertion on map keys

.changesets/add-appsignal-ecto-repo-to-fix-parallel-preloads.md, config/config.exs, lib/appsignal/ecto.ex, lib/appsignal/ecto_repo.ex, test/appsignal/ecto_repo_test.exs, test/appsignal/ecto_test.exs, test/support/fake_ecto_repo.ex
Fixes #603. See also https://github.com/appsignal/appsignal-docs/pull/1715. Use https://github.com/appsignal/test-setups/pull/184 to test it.
Add the `Appsignal.Ecto.Repo` module to fix the Ecto parallel preload issue, making it easy to apply the workaround that was already found by [Elixir Forums][solution] users.
After this change, customers can replace `use Ecto.Repo` in their Ecto repositories with `use Appsignal.Ecto.Repo`. This will configure Ecto so that it passes through the current span at invocation time as the telemetry options for the query, fixing the issue where parallel preload queries were lost because they took place in parallel processes where there was no current span.
For customers who wish to customise their Ecto repo default options, which would override the …
=> Fix Ecto parallel preloads

.changesets/improve-missing-extractor-logs.md, .changesets/remove-deprecated-extension-functions.md, .changesets/update-probes-0.5.4.md, .changesets/update-sql_lexer-0.9.6.md, agent.exs
[skip review]
I didn't clean up these files in the agent repo so they ended up here automatically this release. Remove them.
[skip ci]
Update to the new numbered version matcher.
---
[skip review]
=>  Bump agent to version 0.31.2

config/config.exs, lib/appsignal/tracer.ex, test/appsignal/tracer_test.exs, test/support/tracer.ex
With this function users can add their own function that will be executed right after create_span is called. This allows users to inject data into spans with traces of other tracing providers.
Example
```ex
defmodule MyApp.Appsignal do
def custom_on_create_fun(span) do
Appsignal.Span.set_sample_data(span, "custom_data", %{"foo": "bar"})
end
end
```
Then it can be added to the config with
```ex
config :appsignal, custom_on_create_fun: &MyApp.Appsignal.custom_on_create_fun/1
```
After opening the PR  [Optional fun argument for attach](https://github.com/appsignal/appsignal-elixir-phoenix/pull/80) in here @unflxw mentioned adding the option to this library and executing it on the `create_span/3`.
=> Optional user definable custom function on_create_span/2

.semaphore/semaphore.yml, .semaphore/semaphore.yml.erb
Ubuntu 18 is in a "burnout phase" and won't run any builds anymore.
[skip review]
=> Update build machine for CI

.changesets/drop-non-500-plug-errors-in-add_error-3.md, lib/appsignal/span.ex, test/appsignal/span_test.exs
Plug sets an attribute named plug_status on each of its raised exceptions, which appsignal-plug uses to filter non-500 errors out. This patch moves that filtering to the add_error/3 function, allowing the integration to properly filter exceptions originating in plug, even if they are not caught by the Plug integration.
=> Drop non-500 errors in add_error/3

test/appsignal/error_test.exs
Function clause errors include the blame, which exposes the arguments in the function call. This patch adds a test to make sure those don't leak to AppSignal, and won't in the future.
=> Add regression test for function_clause errors

.changesets/implement-ignore-logs.md, agent.exs, lib/appsignal/config.ex, test/appsignal/config_test.exs
Read the `ignore_logs` config option from `config.exs`, or the `APPSIGNAL_IGNORE_LOGS` environment variable, and re-export it for the AppSignal agent as the `_APPSIGNAL_IGNORE_LOGS` environment variable.
[skip changeset] because the corresponding changeset will be added (modified slightly) from the [agent PR][agent]
[agent]: appsignal/appsignal-agent#1127
=> Add `ignore_logs` configuration option

.changesets/fix-phoenix-filter_parameters-partial-key-matches-support.md, lib/appsignal/config.ex, lib/appsignal/utils/map_filter.ex, test/appsignal/config_test.exs, test/appsignal/utils/map_filter_test.exs
The Phoenix Logger filters out partial keys matches. Our implementation for Phoenix's filter_parameters did not follow this implementation. This change adds support for filtering out partial key matches when using the discard filtering strategy.
Phoenix implementation:
https://github.com/phoenixframework/phoenix/blob/dfb0c00d2077e10f8df6cc6e334e04924c4c2bcd/lib/phoenix/logger.ex#L157-L199
Fixes #936
=> Fix Phoenix filter_parameters partial keys support

.changesets/add-logs-to-probes.md, config/config.exs, lib/appsignal/probes/probes.ex, test/appsignal/probes/probes_test.exs, test/support/appsignal/fake_integration_logger.ex
This test I can't really tell how it asserts that the probe was not run or that it not crashes the process, as it errors silently.
Add another probe that is run successfully and check if it has run more than once. That means the other probe must have also run and raised an error.
Don't use the same probe name as all the other ones. I ran into a random test failure where it was registered, but I don't think it was the one from this test. It might have been another test case.
Get more insights into the operation of the minutely probes by logging what it's doing (which probes it's running) and if it encounters an error.
These logs follow the same format as the Ruby gem.
Resolves #754 because it now logs when it times out a probe.
For some reason `update` caused the following error sometimes …
=> Log probe status and errors to the integration log

.changesets/add-set_name_if_nil-for-span-api.md, .changesets/add-span-set_name_if_nil-helper.md, agent.exs, c_src/appsignal_extension.c, lib/appsignal/nif.ex, lib/appsignal/span.ex, lib/appsignal/test/span.ex, test/appsignal/span_test.exs, test/support/appsignal/test_nif.ex
Add helper to not set the name on a span if it's already set. We can use this to only set the span name (and the root span's (action) name), to not overwrite custom (action) names set by the app.
This change requires an update to the extension.
See PR https://github.com/appsignal/appsignal-agent/pull/1158
Part of #869
=> Add set_name_if_nil helper

.changesets/report-graphql-operation-name-as-absinthe-action-name.md, lib/appsignal/absinthe.ex, test/appsignal/absinthe_test.exs
Group GraphQL requests handled by Absinthe by the GraphQL operation name. Operation names are optional in GraphQL queries, so only set it if it's present.
This uses the new `Span.set_name_if_nil` helper to only set this name if it isn't set by another instrumentation hook or customized by the app.
Fixes https://github.com/appsignal/support/issues/283
---
This also requires a change to the Phoenix integration to use `set_name_if_nil`: https://github.com/appsignal/appsignal-elixir-phoenix/pull/88
=> Group Absinthe GraphQL requests by operation name

mix.exs
Credo 1.7.7 dropped support for Elixir versions below 1.13. This patch locks the credo version to 1.7.6 on any Elixir version before 1.13.
=> Lock credo to 1.7.6 on Elixir < 1.13

.changesets/don-t-run-the-insallation-script-on-windows.md, lib/mix/tasks/appsignal.install.ex
Windows is not a supported OS. Therefore, the installation script shouldn't run when on this system.
This commit adds a check before the script runs. If the system is Windows based, the installation won't run and a message will be shown.
Closes https://github.com/appsignal/support/issues/308
=> Don't run the installation script on windows

dialyzer.ignore-warnings
IO's module `binwrite/2` function no longer returns an error touple when
failing. Instead, it raises an Erlang error. This commit makes dialyzer
ignore that warning so it behaves appropriately in newer and older
versions.
Ref: https://github.com/elixir-lang/elixir/blob/v1.17.1/lib/elixir/lib/io.ex#L280-L284
=> Ignore binwrite error response handling warning

dialyzer.ignore-warnings, lib/mix/tasks/appsignal.install.ex, mix.exs
Previously, the repository included a Dialyzer ignore file with a couple
of ignored warnings. This patch fixes all warnings and removes the file.
=> Fix Dialyzer warnings and remove ignore file

lib/appsignal.ex, lib/appsignal/absinthe.ex, lib/appsignal/config.ex, lib/appsignal/demo.ex, lib/appsignal/diagnose/agent.ex, lib/appsignal/diagnose/host.ex, lib/appsignal/diagnose/library.ex, lib/appsignal/ecto.ex, lib/appsignal/ecto_repo.ex, lib/appsignal/error/backend.ex, lib/appsignal/finch.ex, lib/appsignal/heartbeat.ex, lib/appsignal/instrumentation.ex, lib/appsignal/instrumentation/decorators.ex, lib/appsignal/integration_logger.ex, lib/appsignal/logger.ex, lib/appsignal/monitor.ex, lib/appsignal/oban.ex, lib/appsignal/probes/erlang_probe.ex, lib/appsignal/probes/probes.ex, lib/appsignal/span.ex, lib/appsignal/tesla.ex, lib/appsignal/tracer.ex, lib/appsignal/transmitter.ex, lib/appsignal/utils.ex, lib/appsignal/utils/hostname.ex, lib/mix/tasks/appsignal.diagnose.ex, mix_helpers.exs
AppSignal  for Elixir supports the Elixir and OTP versions listed on the [compatibility page](https://hexdocs.pm/elixir/main/compatibility-and-deprecations.html). Currently, that's Elixir 1.13 and up, and therefore OTP 25 and up.
However, we don't tend to remove old versions from CI until they start giving us issues. When switching the CI to GitHub actions, we found that we could no longer install OTP versions lower than 24, as they're incompatible with the Ubuntu version we're running. Instead of trying to compile from source, we decided to drop Elixir 1.9.x and 1.10.x. Currently, the CI runs Elixir 1.11 and up, and OTP 24 and up.
By dropping these versions, we were able to remove some code we added for compatibility with versions before Elixir 1.11:
1. `Appsignal.Utils.warning/1` was …
=> Drop Elixir versions before 1.11

.github/workflows/ci.yaml
Because of build issues, replace the main/master versions from the CI and run on the latest released versions instead. 
We'd still want to run the CI on unreleased versions, so a pull request is incoming that puts them back. We can then track that to see if the issues resolve.
=> Switch off master and main versions to fix CI

.github/workflows/ci.yaml
To ensure CI runs the latest released Elixir version, add "latest" to the matrix.
=> Add latest Elixir version to CI

.github/workflows/ci.yaml
Removed in #954, this patch restores the Elixir main and Erlang master versions on CI.
=> Add Elixir main to CI

.changesets/fix-ecto-transactions-in-parallel-preloads.md, lib/appsignal/ecto.ex, test/appsignal/ecto_test.exs
This should fix a customer-reported issue ([Intercom link](https://app.intercom.com/a/inbox/yzor8gyw/inbox/conversation/16410700348838#part_id=comment-16410700348838-21909570055)) where an Ecto transaction performed inside an Ecto parallel preload causes the transaction to be closed early.
It makes sense to me, going from the event timelines reported by the customer, that this is the issue that is taking place: the sample showing the error, where `Appsignal.Ecto.Repo` is used, doesn't show the overarching transaction event or the query within it (because the transaction event is never closed and the query event is orphaned) which are present in the sample where `Ecto.Repo` is used, and it shows a lone commit event, which instead of closing the transaction (its tracer parent, within its …
=> Fix ecto transaction in parallel preload

.changesets/make--appsignal-ecto-repo--s--default_options-1--function-overridable.md, lib/appsignal/ecto_repo.ex, test/appsignal/ecto_repo_test.exs, test/support/fake_ecto_repo.ex
I thought this could be the cause of the issue fixed in #958, but I don't think it is anymore. Still, better to fix this corner case before it pokes someone.
Our `Appsignal.Ecto.Repo`, which is meant to be a swap-in replacement for `Ecto.Repo`, should both call `super` on the original `Ecto.Repo` implementation of `default_options` that it overrides, and allow `super` to be called on it by modules that override `default_options`.
=> Follow `@defoverridable` protocol in Ecto repo

c_src/appsignal_extension.c, lib/appsignal/nif.ex, test/appsignal/nif_test.exs
This package uses the Span API. The Transaction API isn't used anymore. Remove the C-extension and Nif code that still call it. Our deprecated Transaction API in Elixir is no-op and doesn't call these Nif functions so we can safely remove them.
=> Remove Transaction Nif code

.changesets/add-heartbeat-check-ins.md, config/config.exs, lib/appsignal/check_in/check_in.ex, lib/appsignal/check_in/cron.ex, lib/appsignal/check_in/event.ex, lib/appsignal/check_in/heartbeat.ex, lib/appsignal/check_in/scheduler.ex, test/appsignal/check_in/check_in_test.exs, test/appsignal/check_in/event_test.exs, test/appsignal/check_in/scheduler_test.exs, test/support/appsignal/fake_scheduler.ex
Part of https://github.com/appsignal/integration-guide/issues/169.
Add an `Appsignal.CheckIn.heartbeat` helper that emits a single heartbeat for the check-in identifier given.
When called with `continuous: true` as the second argument, it starts and links a separate Elixir process that emits a heartbeat every thirty seconds.
Unlike the equivalent functionality in the Ruby integration, which spawns a thread that will stay alive for the lifetime of the Ruby process, the Elixir process is linked to the process that spawned it, meaning it will be shut down when its parent process is shut down. This allows it to be used to track the lifetime of individual Elixir processes.
Additionally, it is also possible to add `Appsignal.CheckIn.Heartbeat` as a child process to a supervisor, meaning its …
=> Implement heartbeat check-ins

.github/workflows/ci.yaml
Trigger CI builds on new PR creation. This also allows us to run the CI for PRs from forks.
The main and develop branch will also run when pushed.
[skip review]
=> Update config for CI

mix.exs
The `compile.appsignal` task requires dependencies like Jason and Hackney to function. Use `@requirements "loadpaths"` so that the dependencies are loaded when running `mix compile.appsignal`.
=> Load dependencies for `compile.appsignal` task

.changesets/fix-warning-for-tesla.md, lib/appsignal/tesla.ex
Fix the following warning when compiling against Elixir 1.17.x:
```
warning: using map.field notation (without parentheses) to invoke function [...].Client.__middleware__() is deprecated, you must add parentheses instead: remote.function()
(appsignal 2.13.0) lib/appsignal/tesla.ex:113: Appsignal.Tesla.module_middlewares/1
(appsignal 2.13.0) lib/appsignal/tesla.ex:106: Appsignal.Tesla.env_middlewares/1
(appsignal 2.13.0) lib/appsignal/tesla.ex:45: Appsignal.Tesla.do_tesla_request_start/2
(telemetry 1.3.0) [...]/elixir/deps/telemetry/src/telemetry.erl:167: anonymous fn/4 in :telemetry.execute/3
(stdlib 6.1.2) lists.erl:2310: :lists.foreach_1/2
(tesla 1.12.1) lib/tesla/middleware/telemetry.ex:96: Tesla.Middleware.Telemetry.call/3
(appsignal 2.13.0) lib/appsignal/instrumentation.ex:10: …
```
=> Use parentheses when accessing Tesla's `__middleware__/0`

.changesets/add--reported_by--tag-to-errors-reported-by-the-legacy-error-backend.md, lib/appsignal/error/backend.ex, test/appsignal/error/backend_test.exs
Motivated by [this Intercom conversation](https://app.intercom.com/a/inbox/yzor8gyw/inbox/admin/5246522/conversation/16410700366093).
We get support tickets about incomplete error reporting, which we assume is due to the use of the error backend. Often customers do not know whether the error was raised from an uninstrumented context, or whether they're using a version of the integration where the error backend is enabled by default.
This should simplify the support workflow for it going forward, by giving us that information in the error sample itself. We can also ask customers to update to the latest version and see if the affected samples have this tag.
This follows the format that we use in [the Ruby integration][ruby].
[ruby]: …
=> Add `reported_by` tag to error backend errors

.changesets/fix-check-ins-not-being-sent-after-some-time.md, lib/appsignal.ex, lib/appsignal/check_in/scheduler.ex, lib/appsignal/diagnose/report.ex, lib/appsignal/transmitter.ex, lib/appsignal/utils/push_api_key_validator.ex, test/appsignal/transmitter_test.exs, test/support/appsignal/fake_transmitter.ex
This relates to the issue reported in https://github.com/appsignal/appsignal-elixir/issues/970, where the default Hackney
pool is drained of connections by the check-ins sent by the
transmitter. This does not fix the issue, but ensures that it is
a separate pool, used only by the AppSignal transmitter, that is
drained of connections, rather than the default one, which may be
used by the customer's code.
Make sure that Hackney connections are closed after use. This fixes
an issue where the Hackney pool does not correctly claim back
connections, which fixes https://github.com/appsignal/appsignal-elixir/issues/970.
Implement a `transmit_and_close/3` convenience method in the
transmitter for use cases where the body is not of interest, meaning
that the connection can be immediately closed.
=> Fix Hackney pool saturation

.changesets/close-spans-on-error.md, lib/appsignal/instrumentation.ex, test/appsignal/instrumentation_test.exs
When our `Appsignal.instrument` function encounters an error when the function argument raises an error, the span it created would not be closed.
Wrap the function call in a `try` block, and move the close logic to an `after` block to ensure that the span is always closed.
I don't know if `instrument_root` is actually used anywhere. We don't call it anywhere and we haven't documented it, but I'm updating it just in case to match the `instrument` helper function.
Related internal thread:
https://appsignal.slack.com/archives/C7XHXQ7N0/p1739893354569399?thread_ts=1739870246.417719&cid=C7XHXQ7N0
=> Close spans on error

.changesets/switch-hackney-with-finch.md, .changesets/switch-the-internal-http-client--hackney--with-finch.md, lib/appsignal.ex, lib/appsignal/check_in/scheduler.ex, lib/appsignal/diagnose/report.ex, lib/appsignal/finch.ex, lib/appsignal/transmitter.ex, lib/appsignal/utils/push_api_key_validator.ex, lib/mix/tasks/appsignal.diagnose.ex, mix.exs, mix_helpers.exs, test/appsignal/diagnose/report_test.exs, test/appsignal/finch_test.exs, test/appsignal/transmitter_test.exs, test/support/appsignal/fake_transmitter.ex, test/support/fake_finch.ex, test/support/fake_hackney.ex
**Transition the HTTP client usage from Hackney to Finch to optimize
requests performance.**
Two versions of transmissions are required now, as Finch needs to be run
under the supervision tree. One version is a standalone transmission
that starts and kills the process as soon as the requests is made, and
the other one uses the pool that's created when the integration starts.
Fixes #978
Fixes #981
=> Switch Hackney to Finch

.changesets/switch-the-internal-http-client--hackney--with-finch.md
Remove a duplicated changeset to avoid repeating information in the changelog.
=> Remove extra changeset

.changesets/fix-check-in-scheduler.md, lib/appsignal/check_in/scheduler.ex, lib/appsignal/transmitter.ex, lib/appsignal/utils/push_api_key_validator.ex, test/appsignal/check_in/scheduler_test.exs, test/support/appsignal/fake_transmitter.ex
Fixes #988. See #983 for context.
---
Remove `Transmitter.transmit_and_close` method. This method existed due to some scenarios where a Hackney connection would be kept open for its body to be read, saturating the Hackney pool.
As such, we previously changed how the transmitter worked, so that either you call `.transmit`, and you're responsible for reading the body and closing the request, or you call `.transmit_and_close`, which takes care of closing the request for you, but does not provide access to the body.
Finch does not seem to have such issues, and as such there is no need for this convenience method.
In the push API key validator, don't assume that the error returned by Finch (which is passed through by `Transmitter.transmit`) is a `Mint.TransportError` with a `:reason` key. …
=> Fix Finch usage in check-in scheduler

.changesets/fix-crashes-when-failing-to-send-check-ins.md, lib/appsignal/check_in/scheduler.ex, lib/mix/tasks/appsignal.diagnose.ex, test/appsignal/check_in/scheduler_test.exs, test/mix/tasks/appsignal_diagnose_test.exs
Some error types, such as `Mint.TransportError`, which is returned to us via Finch, do not implement `String.Chars`, and as such cannot be printed directly.
Use `inspect` when printing an error obtained (directly or indirectly) from a `.transmit` `{:error, error}` tuple.
=> Do not crash on non-printable errors

.changesets/add-mix-task-to-check-the-extension-install.md, lib/appsignal/utils/tasks.ex, lib/mix/tasks/appsignal.check_install.ex, test/mix/tasks/appsignal_check_install_test.exs
In a support conversation we discussed how adding a mix task that can check if AppSignal's NIF and agent were successfully installed.
We don't fail the installation if these couldn't be installed because we don't want to breaks applications and prevent them from starting, potentially bringing down whole applications. We rather not report data to AppSignal in this scenario.
For people who do want this behavior, they can run this task before they start their application or as part of their CI.
https://app.intercom.com/a/inbox/yzor8gyw/inbox/shared/all/conversation/16410700412377#part_id=comment-16410700412377-21909590891
=> Add mix appsignal.check_install task

.changesets/allow-keyword-list-configurations.md, lib/appsignal/config.ex
Previously, functions like minutely_probes_enabled?/0 used Map.get/3 to get values from the configuration. In some situations, the configuration is a keyword list. By using Access.get/3 both versions are supported.
=> Use Access.get/3 for boolean configuration helpers

.changesets/remove-redundant-cron-check-in-pairs.md, lib/appsignal/check_in/event.ex, lib/appsignal/check_in/scheduler.ex, test/appsignal/check_in/event_test.exs
See https://github.com/appsignal/appsignal-ruby/pull/1407 for context. This commit reimplements that in Elixir.
Before submitting a batch of cron check-in events, check for any pairs of events that are redundant with other pairs of cron check-in events. This would happen, for example, when running a `cron` block for a given identifier many times in quick succession.
A redundant pair of cron check-in events is a pair of start and finish cron check-in events for a given identifier, given that another pair of start and finish check-in events exists for that identifier.
=> Remove redundant cron check-in pairs

.changesets/report-oban-configuration-prefix-as-a-tag.md, lib/appsignal/oban.ex, test/appsignal/oban_test.exs
Following up on #997. See also test setup: https://github.com/appsignal/test-setups/pull/295
Report the `:prefix` key of the Oban configuration as a tag, if present.
=> Report Oban configuration prefix as tag

.changesets/fix-oban-result-attribute.md, lib/appsignal/oban.ex, test/appsignal/oban_test.exs
First, split out the result value into its expected tuple values. Only store expected value formats, and not any random value the Oban worker's `perform` function can return.
This prevents us storing unintended and potentially sensitive data.
Store the reasons for discard, cancel and snooze result into a new `result_reason` field, so it's easier to search by. The ok reason is ignored, matching the Oban.Worker's result type.
Source:
https://hexdocs.pm/oban/Oban.Worker.html#t:result/0
- [Support conversation](https://app.intercom.com/a/inbox/yzor8gyw/inbox/conversation/215468907591572?view=List)
=> Improve Oban result attribute

.github/workflows/ci.yaml
Let us see the result of all jobs and not exit all running jobs when one fails.
[skip review]
=> Disable fail fast on CI workflow

.changesets/add--nginx_port--configuration-option.md, lib/appsignal/config.ex, test/appsignal/config_test.exs
**⚠️ This PR cannot be merged until a release of the agent containing appsignal/appsignal-agent#1275 has been released and its agent file merged into this repository. ⚠️** 
Implement an `nginx_port` configuration option that is passed on to the agent, like the existing `statsd_port` and `opentelemetry_port` configuration options.
=> Add `nginx_port` configuration option

.github/workflows/ci.yaml, test/appsignal/integration_logger_test.exs
Add OTP 28 and Elixir 1.18.x to the CI matrix.
Closes #998
=> Add support for OTP 28

test/appsignal/error/backend_test.exs
It looks like the `do end` block no longer works for `catch_exit`.
The only thing it seems to do is catch an exit if one occurs, not assert if it happens. If we remove it the tests fails on the errors we assert on the spans that bubble up from the GenServer.
Directly pass in the GenServer call, like in the docs example:
```elixir
assert catch_exit(exit(1)) == 1
```
https://hexdocs.pm/ex_unit/ExUnit.Assertions.html#catch_exit/1
=> Fix compilation on Elixir main
