lib/appsignal/config.ex
lib/appsignal/transaction.ex
test/appsignal_transaction_test.exs

A first stab at filtering parameters via the config.

Filter parameters

---

lib/appsignal.ex
lib/appsignal/error_handler.ex
lib/appsignal/transaction.ex
test/appsignal_test.exs
test/error_handler/appsignal_error_handler_test.exs
test/error_handler/appsignal_error_matcher_test.exs
test/transaction/transaction_test.exs

Send metadata in Appsignal.ErrorHandler.submit_transaction/6

---

mix_helpers.exs

Mapping the centos/redhat linux arch

Added centos/redhat support for agent installation

---

config/config.exs
lib/appsignal.ex
lib/appsignal/transaction/registry.ex
test/appsignal_test.exs
test/instrumentation/decorator_test.exs
test/phoenix/plug_test.exs
test/test_helper.exs
test/transaction/registry_test.exs

Check Appsignal.started?/1 in TransactionRegistry.lookup/2

---

agent.json

Update agent to 5f0c552

---

lib/appsignal/config.ex
test/config/appsignal_config_test.exs

Enable host metrics by default

---

lib/appsignal/instrumentation/decorators.ex
test/instrumentation/decorator_test.exs

Add a transcation decorator

---

GettingStarted.md

Related PR https://github.com/appsignal/appsignal-docs/pull/73
Submitting a PR so you can check if this is accurate

Fix filter params config docs in GettingStarted.md

---

lib/appsignal.ex
test/appsignal/appsignal_test.exs

Allow passing a function to Appsignal.send_error/6

---

c_src/appsignal_extension.c

Send body->data instead of body to appsignal_finish_event

---

lib/appsignal/config.ex
test/appsignal/config_test.exs

Closes #94. Depends on https://github.com/appsignal/appsignal-agent/pull/217.

Remove automatic :running_in_container setting

---

lib/appsignal.ex
lib/appsignal/config.ex
lib/appsignal/error_handler.ex
lib/appsignal/nif.ex
lib/appsignal/phoenix.ex
lib/appsignal/phoenix/instrumenter.ex
lib/appsignal/phoenix/template_instrumenter.ex
lib/appsignal/transaction.ex

The important type of PR ;)
Anyway, PR here only for CI build.

AppSignal, not Appsignal

---

lib/appsignal/utils/push_api_key_validator.ex
lib/mix/tasks/appsignal.diagnose.ex
test/appsignal/utils/push_api_key_validator_test.exs

Code extracted from #125 for easier review. Introducing/extracting the module in the install PR and realized I also used the same logic in the diagnose task.

Extract push api key validator module

---

.gitignore
lib/mix/tasks/appsignal.install.ex
test/mix/tasks/appsignal_install_test.exs

Based on #129 
Part of #45 
Assumes that app names can be strings #133

mix appsignal.install push_api_key

---

mix.exs

Branch based on 0.12.0 to avoid accidentally introducing/breaking behavior for someone that's testing this.
Before merging we should rebase this on the latest develop branch and then merge.

Upgrade HTTPoison and allow more versions

---

config/config.exs
lib/appsignal/demo.ex
lib/mix/tasks/appsignal.install.ex
test/mix/tasks/appsignal_install_test.exs
test/support/fake_demo.ex

Based on #125 
Requires  #135 to be merged otherwise it can't initialize the config twice.
I made it a separate PR otherwise we can't merge the install PR #125 without the config change PR #135

Send demo samples on install

---

agent.ex
c_src/appsignal_extension.c
lib/appsignal/nif.ex
lib/appsignal/transaction.ex

Change record_event arguments after merging the change on the agent
side: https://github.com/appsignal/appsignal-agent/pull/259

Reorder record_event arguments

---

lib/appsignal/transaction.ex
test/appsignal/transaction_test.exs

Transaction.set_request_metadata sets path and method

---

lib/appsignal/plug.ex
lib/appsignal/transaction.ex
test/appsignal/plug_test.exs
test/phoenix/phoenix_test.exs

Extract sample and meta data in Appsignal.Plug, whitelist request headers

---

lib/appsignal/error_handler.ex

Wrap WrapperError clause in Appsignal.plug?

---

lib/agent.ex
test/mix/tasks/appsignal_diagnose_test.exs

Closes #295.
- Fix locking issue on diagnose mode run.

Bump agent to ee63235

---

lib/appsignal/error_handler.ex
test/appsignal/error_handler_test.exs

ErrorHandler doesn't cause warnings for noise over handle_info 

---

lib/appsignal/plug.ex
test/appsignal/plug_test.exs

Add x-real-ip to request header whitelist

---

lib/appsignal/config.ex
test/appsignal/config_test.exs
test/appsignal/release_upgrade_test.exs

As discussed in https://github.com/appsignal/appsignal-elixir/pull/315#discussion_r171902030.

🐞 Underscored environment variables are always overwritten

---

mix.exs

Fixes https://github.com/appsignal/appsignal-elixir/issues/288#issuecomment-376848167.

🐞 Add agent.exs file to package in mix.exs

---

mix.exs

Relax :httpoison dependency to allow ~> 1.0

---

agent.exs

- Fix metrics format for internal agent metrics

Bump agent to e509c90

---

lib/appsignal/diagnose/report.ex
lib/appsignal/utils/push_api_key_validator.ex
mix.exs

Closes https://github.com/appsignal/appsignal-elixir/issues/238.

Use hackney instead of HTTPoison

---

mix.exs
mix_helpers.exs

Use :hackney instead of cURL to download agent

---

CHANGELOG.md
agent.exs
mix.exs

- Fix memory reporting for container systems.
PR for Elixir 1.7.0-alpha.1 release.

Improve memory reporting for container systems

---

agent.exs

- Revert container memory metrics fixes
- Fix _APP_REVISION read logic for Elixir.
- Fix _APPSIGNAL_PROCESS_NAME read logic for Elixir.

Bump agent to v-e801925

---

test/phoenix/channel_test.exs

Fixes test failures on Decorator 1.2.4 on develop.

Create separate modules for testing Appsignal.Phoenix.Channel

---

mix.exs

Fixes
https://github.com/appsignal/appsignal-elixir/pull/403#issuecomment-427859254.

Add :poison to :applications

---

lib/mix/tasks/appsignal.diagnose.ex
test/mix/tasks/appsignal_diagnose_test.exs

This option allows users to (not) send the report without being
prompted. Useful for our support team to send this all in one command to
the user, so users don't have to confirm anything.
```
mix appsignal.diagnose --send-report
mix appsignal.diagnose --no-send-report
```
Also useful for non-interactive environments in which the command is
run.
Based on #412 
Related PR https://github.com/appsignal/appsignal-ruby/pull/438

Add diagnose command --[no-]send-report option

---

lib/appsignal/config.ex
test/appsignal/config_test.exs

Add functions to `Appsignal.Config` to fetch the config options from
every source separately using similar functions. Previously we all
merged the config options in the Application config, which made it
impossible to trace back where what value came from for the config
option.
This sources hash will be included in the diagnose report in a future
commit.
On initialize the different functions are read and stored in the sources
map before they're merged together for the final config.
The new values in the map stored in the Application config contain the
config options set for all the possible sources:
- `default`
returns the default config and runtime config (things we can't
hardcode in the `Appsignal.Config` default_config module attribute).
- `system`
options detected from the system host, …

Fetch and store separate config sources

---

lib/appsignal.ex
lib/appsignal/error_handler.ex
test/appsignal/appsignal_test.exs
test/appsignal/error_handler/error_matcher_test.exs
test/appsignal/error_handler_test.exs
test/support/fake_transaction.ex

Continuation of https://github.com/appsignal/appsignal-elixir/pull/424. Pull request created for CI.

FakeTransaction in ErrorHandler tests

---

.travis.yml

Can be merged after https://github.com/appsignal/appsignal-elixir/pull/432

Error on compilation warnings.

---

lib/appsignal/plug.ex
test/appsignal/plug_test.exs

Continuation of https://github.com/appsignal/appsignal-elixir/pull/452, which was merged by accident.

Add response status codes to Plug samples

---

lib/appsignal/ecto.ex
test/appsignal/ecto_test.exs
test/support/fake_transaction.ex

Update Ecto integration to support both Telemetry 0.3.x and 0.4.x

---

test/appsignal/transaction_test.exs

Wrap System.stacktrace() in try/catch block in Transaction tests

---

agent.exs

- Track memory metrics of the current process.
- Rename process tag name to `process_name`.

Bump agent to d8dc806

---

lib/appsignal.ex

Update send_error examples

---

lib/appsignal.ex
lib/appsignal/instrumentation/decorators.ex
lib/appsignal/phoenix/live_view.ex
mix.exs
test/phoenix/live_view_test.exs

Based on @isavita's pull request in #548, this pull request continues work to finish the work on adding LiveView support, and is drafted to get CI to run tests.

Add LiveView support

---

lib/appsignal/transaction.ex
test/support/appsignal/fake_transaction.ex

Fixes #554 
Additionally, I also added the callbacks for `set_namespace` as they were also missing.

554 add record event callback

---

agent.exs

Fix issue with host metrics values being reported as "Infinity".
[skip review]

Bump agent to v-4548c88

---

agent.exs

Bump agent to v-c8f8185

---

lib/appsignal/instrumentation/decorators.ex
test/appsignal/instrumentation_test.exs

As reported in https://github.com/orgs/appsignal/projects/35#card-50171586, via
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700018106

Use "channel" namespace in channel_action decorator

---

lib/appsignal/ecto.ex
lib/appsignal/transaction.ex
lib/appsignal/transaction_registry.ex

Fixed some warnings

---

lib/appsignal/probes/probes.ex
test/appsignal/probes/probes_test.exs
test/support/fake_probe.ex

Probes.handle_info/2 handles non-exception errors

---

lib/appsignal/ecto.ex
lib/appsignal/instrumentation.ex
lib/appsignal/span.ex
lib/appsignal/tracer.ex
lib/appsignal/transaction_registry.ex

Update typespecs and documentation for `Span`, `Tracer`, `Ecto` and `Instrumentation`

---

.changesets/bump-agent-891c6b0.md
agent.exs

- Bump internal dependencies.
- Add experimental Apple Silicon M1 ARM64 build.
[skip review]

Update agent to v-891c6b0

---

.changesets/bump-agent-0318770.md
agent.exs

- Improve Dokku platform detection. Do not disable host metrics on
Dokku.
- Report CPU steal metric.
[skip review]

Bump to agent 0318770

---

.semaphore/semaphore.yml
lib/appsignal/nif.ex
lib/appsignal/transmitter.ex
test/appsignal/nif_test.exs

I've run `mix format` on the project to make sure other changes I made
were correct. As I did that I noticed some other files were also changed
when it was done. This change updates the project to the latest `mix
format` output.

Run mix.format on project

---

.changesets/bump-agent-to-7376537.md
agent.exs

- Support JSON PostgreSQL operator in sql_lexer.
- Do not strip comments from SQL queries.
[skip review]

Bump agent to 7376537

---

.changesets/bump-agent-to-09308fb.md
agent.exs

- Update sql_lexer dependency with support for reversed operators in
queries.
- Add debug level logging to custom metrics in transaction_debug_mode.
- Add hostname config option to standalone agent.
[skip review]

Bump agent to 09308fb

---

script/setup

Bug fixes and support for changeset types.
[skip review]

Update mono to 0.6.0

---

CHANGELOG.md
mix_helpers.exs
test/appsignal/config_test.exs
test/appsignal/probes/probes_test.exs
test/appsignal/tracer_test.exs
test/mix/tasks/appsignal_diagnose_test.exs

Apply fixes for typo as suggested in PR #738.
[skip review]

Fix typos in project

---

test/appsignal/error/backend_test.exs

Since `Logger` uses Erlang's legacy `:error_logger` instead of the newer
`:logger`, the error backend test with a Plug `conn` failed on OTP 20.
That's caused by a difference in the `:logger` and `:error_logger`
implementations. On OTP < 21, the `:error_logger` runs its translators
in a different process, while the `:logger` (on OTP >= 21) runs the
translators in the same process.
This means that taking `self/0` inside the translator produces a
different pid than the one ignored in the test, which fails the test.
This isn't caused by a failure in the implementation, but rather an
issue in the test setup.
This patch uses a static pid (`<0.123.0>`) on OTP 20. This works by
calling out to `pid/0` and `ignore_pid/0`. The former produces the
static PID on OTP 20, but uses `self/0` on any newer …

Fix error backend with conn test on OTP 20

---

.changesets/bump-agent-bbc830a.md
agent.exs

- Support batched statsd messages
- Set start times for spans with traceparents
- Check duration in transactions for negative and too high values
[skip review]

Bump agent to v-bbc830a

---

.changesets/bump-agent-to-v-f57e6cb.md
agent.exs

- Enable process metrics on Heroku and Dokku
[skip review]

Bump agent to v-f57e6cb

---

.changesets/bump-agent-to-0d593d5.md
agent.exs

- Report shared memory metric state.
[skip review]

Bump agent to 0d593d5

---

c_src/appsignal_extension.c
lib/appsignal/logger.ex
lib/appsignal/logger/backend.ex
lib/appsignal/nif.ex
test/appsignal/logger/backend_test.exs
test/appsignal/logger_test.exs
test/support/appsignal/test_nif.ex

Part of #800 (and based on #829) , this patch adds support for logfmt. 

Add support for logfmt

---

.changesets/bump-agent-to-4a0a036.md
agent.exs

Fix a transmission requeueing problem with queued payloads.
[skip review]

Bump agent to 4a0a036

---

.changesets/update-agent-to-f9b0c15.md
agent.exs

- Add more span API logging.
[skip review]

Update agent to v-f9b0c15

---

.changesets/cgroups-v2-cpu-stats-normalization.md
agent.exs

Normalize cgroups v2 CPU stats.

Bump agent to eec7f7b

---

.changesets/cgroups-v1-cpu-percentage-normalization.md
.changesets/cgroups-v2-fractional-cpu.md
agent.exs

Bump agent to version 0.33.0

---

.changesets/add-opentelemetry-histogram-support.md
agent.exs

Bump agent to version 0.33.1

---

.changesets/fix-opentelemetry-chunked-export-requests.md
agent.exs

Bump agent to version 0.33.2

---

.changesets/log-debug-messages-for-metrics.md
agent.exs

Bump agent to version 0.35.5

---

.changesets/support-kamal-based-deployments.md
agent.exs

Bump agent to version 0.35.10

---

.changesets/change-primary-download-mirror.md
agent.exs

Update agent to version 0.35.26

---

.changesets/set-app-revision-config-option-for-scalingo-deploys.md
agent.exs

Update agent to version 0.35.27

---

.changesets/fix-an-issue-where-the-extension-fails-to-build-on-arm64-linux.md
agent.exs

Update agent to version 0.35.28

---

.changesets/fix-a-performance-issue-when-sanitising--insert-into-----values--queries.md
agent.exs

Update agent to version 0.35.29

---

.changesets/remove-opentelemetry-beta-feature.md
agent.exs

Update agent to version 0.36.0

---

.changesets/delay-and-eventually-prevent-agent-reboots.md
agent.exs

Update agent to version 0.36.1

---

.changesets/improve-sql-sanitisation.md
agent.exs

Update agent to version 0.36.2

---

.changesets/log-debug-message-when-error-is-reported-that-is-ignored.md
agent.exs

Update agent to version 0.36.5
